### ISSUE TITLE
Getbhavcopy Indices Data Issue

### ISSUE THREAD

**Issue by Chhirag** [hemenkapadia/getbhavcopy#1]
Hi Hemen, You asked me to create a table as per GBC's data downloading format, please check whether it is appropriate or otherwise. I haven't added India VIX in the table as it wasn't available. Please fix the issues regarding NSEMIDCAP & NIFTYSMALL100 gbc symbol as converted data is mismatching, whenever you are comfortable. Please don't hesitate to ask if anyway I could cooperate you. 

NSE HISTORICAL DATA SYMBOL ---- GETBHAVCOPY SYMBOL

NIFTY 50 ---- NSENIFTY
NIFTY Next 50 ---- NIFTYJUNIOR
NIFTY100 LIQ 15 ---- NIFTYLIQ15
NIFTY Midcap Liquid 15 ---- NIFTYMIDCAPLIQ15
NIFTY 100 ---- NSE100
NIFTY 200 ---- NIFTY200
NIFTY 500 ---- NSE500
NIFTY Midcap 50 ---- MIDCAP50
NIFTY Free Float Midcap 100 ---- NSEMIDCAP
NIFTY Free Float Smallcap 100  ---- NIFTYSMALL100
NIFTY Auto ---- NIFTYAUTO
NIFTY Bank ---- BANKNIFTY
NIFTY Energy ---- NIFTYENERGY
NIFTY Financial Services ---- NIFTY FINSERVICE
NIFTY FMCG ---- NIFTYFMCG
NIFTY IT ---- NSEIT
NIFTY Media ---- NIFTYMEDIA
NIFTY Metal ---- NIFTYMETAL
NIFTY Pharma ---- NIFTYPHARMA
NIFTY PSU Bank ---- NIFTYPSUBANK
NIFTY Realty ---- NIFTYREALTY
NIFTY Commodities ---- NIFTYCOMMODITIES
NIFTY India Consumption ---- NIFTYCONSUMPTION
NIFTY CPSE ---- NIFTY CPSE
NIFTY Infra ---- NIFTYINFRA
NIFTY MNC ---- NIFTYMNC
NIFTY PSE ---- NIFTYPSE
NIFTY Services Sector ---- NIFTYSERVSECTOR
NIFTY Shariah 25 ---- NIFTYSHARIAH25
NIFTY50 Shariah ---- NIFTY50SHARIAH
NIFTY500 Shariah ---- NIFTY500SHARIAH
NIFTY100 Equal Weight ---- NIFTY100EQUALWEIGHT
NIFTY50 USD ---- NSEDEFTY 
NIFTY50 Dividend Points ---- NIFTY50DIVPOINT
NIFTY Dividend Opportunities 50 ---- NIFTYDIVOPPS50
NIFTY Alpha 50 ---- NIFTYALPHA50
NIFTY High Beta 50 ---- NIFTYHIGHBETA50
NIFTY Low Volatility 50 ---- NIFTYLOWVOL50
NIFTY Quality 30 ---- NIFTYQUALITY30
NIFTY50 Value 20 ---- NIFTY50VALUE20
NIFTY Growth Sectors 15 ---- NIFTYGROWSECT15

Regards,
Chhirag

**Comment by hemenkapadia** [comment]
Thanks @Chhirag , this helps a lot. I will try to include this in next release.

**Comment by Chhirag** [comment]
It's My Pleasure @hemenkapadia , waiting eagerly for your next release. Best Wishes!

**Comment by hemenkapadia** [comment]
Hi @Chhirag , Can you please remind me the ask here?

I recollect asking you to create the mapping above but i am unable to recollect the background discussion. I tried to check any email discussion with you on the topic but could not find those. Would appreciate if you can provide the context.

**Comment by Chhirag** [comment]
Sure @hemankapadia Bhai, in fact prior to the current version of GBC, under the GETBHAVCOPY Symbol "NSEMIDCAP" & "NIFTYSMALL100" we were getting the data of NSE Historical Data Symbol "NIFTY MID100 FREE" & "NIFTY SML100 FREE" respectively instead of "NIFTY FULL MIDCAP 100" & "NIFTY FULL SMALLCAP 100" which we are getting post release of current version of GBC. This not only created a data mismatch but inconvenient part is that we are unable to analyze the full Midcap & Smallcap sector trends because both "NIFTY FULL MIDCAP 100" & "NIFTY FULL SMALLCAP 100" furnishes only the Closing prices instead of O,H,L,C. 

Apart from the above, I'ld like to bring one more issue under your consideration about the error in getting data from BSE Servers as highlighted by some other members as well. Regarding this issue I had mailed you earlier as well on 15th of July last year.

Gratefulness is just not enough to express my respect towards your selfless help to me & many people as me who are totally depend and rely on your software for getting the accurate data directly from the Exchange Servers. If you could manage some time out from your busy schedule & fix the above mentioned issues it will really be a great help.

Thanks & Warm Regards

Chhirag Kedia

**Comment by hemenkapadia** [comment]
Thanks @Chhirag , the issue with BSE Indices data download is being tracked in issue #17 .

I will not be fixing the NSE issue for now. I am deciding to revamp GBC completely and will need to come up with the NSE Indices strategy - possibly configurable options, still need to decide how it is going to be.

2.1.11a will be released in a day or two just to get the BSE indices working again.

**Comment by Chhirag** [comment]
No Worries @hemenkapadia bhai, if even BSE Data issue get resolved it still be a big help. When you were busy last days, I asked one of my software developer friend for help, he told me that its Source files aren't available- is it possible for you to share source files so in case you remain busy, we may tweak it a bit if required..

**Comment by hemenkapadia** [comment]
NSE indices mismatch data issue would get resolved with the complete rewrite of the mapping. While not adhering to the exact list shared by Chirag above, it will confirm with the NSE Indices list on https://www.nseindia.com/products/content/equities/indices/historical_index_data.htm

**Comment by hemenkapadia** [comment]
Link to issue #33

**Comment by hemenkapadia** [comment]
code complete

**Comment by Chhirag** [comment]
Dear Heman,
I hope you are doing good. Getbhavcopy had stopped working from 5th Dec.
Few people had already raised a ticker there on github. As we are dependent
on it for our analysis, stopping it is creating a lot of problems. Can you
pls take some time out & fix it?

Regards,
Chhirag
