### ISSUE TITLE
retry downloading of index data

### ISSUE THREAD

**Issue by tjagad** [hemenkapadia/getbhavcopy#10]
It seems that nse and bse servers don't respond many times with data specially when downloading index data. Is it possible to provide and option to retry downloading index data in the settings box.

**Comment by tjagad** [comment]
It's quite common to get "Error	The remote server returned an error: (500) Internal Server Error." for BSE data.

On NSE front the message is "Error	NSE server did not return data for index NSEDEFTY"


Entire Log below for reference. 

Message	*********  Starting Getbhavcopy  *********
Message	Downloading symbols for index NSENIFTY
Message	Downloading symbols for index NIFTYJUNIOR
Message	Downloading symbols for index NSE100
Error	Error downloading symbols for index NSE100 from https://www.nseindia.com/content/indices/ind_cnx100list.csv
Error	The remote server returned an error: (404) Not Found.
Message	Downloading symbols for index NSE500
Error	Error downloading symbols for index NSE500 from https://www.nseindia.com/content/indices/ind_cnx500list.csv
Error	The remote server returned an error: (404) Not Found.
Message	Downloading symbols for index MIDCAP50
Message	Downloading symbols for index NSEMIDCAP
Error	Error downloading symbols for index NSEMIDCAP from https://www.nseindia.com/content/indices/ind_cnxmidcaplist.csv
Error	The remote server returned an error: (404) Not Found.
Message	Downloading symbols for index BANKNIFTY
Error	Error downloading symbols for index BANKNIFTY from https://www.nseindia.com/content/indices/ind_cnxbanklist.csv
Error	The remote server returned an error: (404) Not Found.
Message	Downloading symbols for index NSEIT
Error	Error downloading symbols for index NSEIT from https://www.nseindia.com/content/indices/ind_cnxitlist.csv
Error	The remote server returned an error: (404) Not Found.
Message	*********  Downloading Data for 20-12-2017  *********
Message	Downloading NSE Equity Bhavcopy
Message	Downloading index data for NSENIFTY
Message	Downloading index data for NIFTYJUNIOR
Message	Downloading index data for NIFTYLIQ15
Message	Downloading index data for NIFTYMIDCAPLIQ15
Message	Downloading index data for NSE100
Message	Downloading index data for NIFTY200
Message	Downloading index data for NSE500
Message	Downloading index data for MIDCAP50
Message	Downloading index data for NSEMIDCAP
Message	Downloading index data for NIFTYSMALL100
Message	Downloading index data for NIFTYAUTO
Message	Downloading index data for BANKNIFTY
Message	Downloading index data for NIFTYENERGY
Message	Downloading index data for NIFTYFINSERVICE
Message	Downloading index data for NIFTYFMGC
Message	Downloading index data for NSEIT
Message	Downloading index data for NIFTYMEDIA
Message	Downloading index data for NIFTYMETAL
Message	Downloading index data for NIFTYPHARMA
Message	Downloading index data for NIFTYPSUBANK
Message	Downloading index data for NIFTYREALTY
Message	Downloading index data for NIFTYCOMMODITIES
Message	Downloading index data for NIFTYCONSUMPTION
Message	Downloading index data for NIFTYCPSE
Message	Downloading index data for NIFTYINFRA
Message	Downloading index data for NIFTYMNC
Message	Downloading index data for NIFTYPSE
Message	Downloading index data for NIFTYSERVSECTOR
Message	Downloading index data for NIFTYSHARIAH25
Message	Downloading index data for NIFTY50SHARIAH
Message	Downloading index data for NIFTY500SHARIAH
Message	Downloading index data for NIFTY100EQUALWEIGHT
Message	Downloading index data for NSEDEFTY
Error	NSE server did not return data for index NSEDEFTY
Message	Downloading index data for NIFTY50DIVPOINT
Message	Downloading index data for NIFTYDIVOPPS50
Message	Downloading index data for NIFTYALPHA50
Message	Downloading index data for NIFTYHIGHBETA50
Message	Downloading index data for NIFTYLOWVOL50
Message	Downloading index data for NIFTYQUALITY30
Message	Downloading index data for NIFTY50VALUE20
Message	Downloading index data for NIFTYGROWSECT15
Message	Downloading index data for VIX
Message	Downloading Deliverable Quantity(Open Interest) data
Message	Processing downloaded data
Message	*********  NSE Equity Bhavcopy file generated  *********
Message	Downloading NSE Futures Bhavcopy
Message	Processing downloaded data
Message	*********  NSE Futures Bhavcopy file generated  *********
Message	Downloading BSE Equity Bhavcopy
VIEWSTATE obtained successfully
Message	Downloading index data for SENSEX
Message	Downloading index data for BSE-100
Message	Downloading index data for BSE-200
Message	Downloading index data for BSE-500
Message	Downloading index data for ALLCAP
Error	Error sending Index Data HTTP POST for ALLCAP
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for AUTO
Error	Error sending Index Data HTTP POST for AUTO
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for BANKEX
Error	Error sending Index Data HTTP POST for BANKEX
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for BASICMAT
Error	Error sending Index Data HTTP POST for BASICMAT
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for CAPGOODS
Error	Error sending Index Data HTTP POST for CAPGOODS
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for CONDDISC
Message	Downloading index data for CONSDURBL
Error	Error sending Index Data HTTP POST for CONSDURBL
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for CPSE
Error	Error sending Index Data HTTP POST for CPSE
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for DOL-30
Error	Error sending Index Data HTTP POST for DOL-30
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for DOL-100
Error	Error sending Index Data HTTP POST for DOL-100
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for DOL-200
Error	Error sending Index Data HTTP POST for DOL-200
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for ENERGY
Error	Error sending Index Data HTTP POST for ENERGY
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for FMCG
Message	Downloading index data for FINANCE
Message	Downloading index data for HLTHCARE
Message	Downloading index data for INFRA
Error	Error sending Index Data HTTP POST for INFRA
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for MANUFACTURING
Error	Error sending Index Data HTTP POST for MANUFACTURING
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for INDUSTRIAL
Message	Downloading index data for IT
Error	Error sending Index Data HTTP POST for IT
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for METAL
Error	Error sending Index Data HTTP POST for METAL
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for MIDCAP
Error	Error sending Index Data HTTP POST for MIDCAP
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for SMLCAP
Error	Error sending Index Data HTTP POST for SMLCAP
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for OILGAS
Message	Downloading index data for POWER
Error	Error sending Index Data HTTP POST for POWER
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for PSU
Message	Downloading index data for REALTY
Message	Downloading index data for TECK
Error	Error sending Index Data HTTP POST for TECK
Error	The remote server returned an error: (500) Internal Server Error.
Message	Downloading index data for TELECOM
Message	Downloading index data for UTILITIES
Message	Downloading index data for CARBONEX
Message	Downloading index data for GREENEX
Error	Error sending Index Data HTTP POST for GREENEX
Error	The remote server returned an error: (500) Internal Server Error.
Message	Processing downloaded data
Message	*********  BSE Equity Bhavcopy file generated  *********
Message	********* Data download complete *********

**Comment by hemenkapadia** [comment]
@tjagad , looking at your logs I notice you are downloading the constituent symbols for the indices. That was an old feature when Index volume data was not readily available for NSE and Getbhavcopy had to calculate the index volume. That is no longer the case so you should look at your options.

**Comment by hemenkapadia** [comment]
@tjagad , now coming to the problem of intermittent HTTP errors and retry, how often is this? If it is too often and there are multiple people who upvote the issue then I will try to add that feature.
For now this is in the backlog.

**Comment by hemenkapadia** [comment]
Hmm, not sure if you enabled this feature due to #9 . Need to investigate.

**Comment by tjagad** [comment]
@hemenkapadia Yeah i had the option to calculate index volume in my options. Disabling that removes the initial erros now.

Regarding the HTTP errors, they are quite frequent lately and it seems to be an issue with the bse webiste lately.

I didn't quite understand your last comment.

**Comment by hemenkapadia** [comment]
To summarize the ask here is to add a retry option for downloading index data.

**Comment by hemenkapadia** [comment]
Closing, wont fix
