### ISSUE TITLE
Getvhavcopy v2.1.15a not working

### ISSUE THREAD

**Issue by vivekmba05** [hemenkapadia/getbhavcopy#100]
Data is not downloading since yesterday.

Following msg is appearing.
![GBC](https://user-images.githubusercontent.com/46931266/68212551-bf230f00-ffff-11e9-9b38-f78e05d32bb9.JPEG)

The underlying connection was closed: An unexpected error occurred on a send.

Kindly do the needful.

**Comment by hemenkapadia** [comment]
@vivekmba05, can you please download the latest version of Getbhavcopy from https://github.com/hemenkapadia/getbhavcopy/releases and try again?

Please refer to my response in issue #96 where I did test and confirm that the latest version of Getbhavcopy seems to be working fine for me.

**Comment by vivekmba05** [comment]
I have Windows 7 ultimate and i tired installing GBC 3.0 version but .NETframework 4.6 cant be installed. It says current OS does not support .NET Framework 4.6

**Comment by vivekmba05** [comment]
Download of latest version is not working , it says that the OS does not
support .NET Framework 4.6.

But I have Windows 7 Ultimate OS.


Warm Regards,
R.Vivek
For Jaya Bharat Finmart
Salem. (T.N)
Off : 0427 - 4050575.
Cell: 93444 - 08575.
