### ISSUE TITLE
GetBhavcopy not working since 4 Nov. 2019

### ISSUE THREAD

**Issue by sreenigki** [hemenkapadia/getbhavcopy#101]
1) GetBhavcopy is loading but not able to download Bhavcopy esp for NSE and also for NSE Futures.

2) While Downloading NSE Futures OI data, the data goes to wrong contracts.   For example, current month contract data goes to contract  ****-3, next month contract goes to contract ****-2 and so forth.  I request you to kindly verify this and hope to get it rectified while releasing your next update.

Thanks in advance
Srinivas, Bangalore

**Comment by neerajmsr** [comment]
me too having same problem. earlier bse was not working till today, now nse too not working...please look into it

thanking you
neeraj

**Comment by hemenkapadia** [comment]
@sreenigki AND @neerajmsr, I checked the latest version of Getbhavcopy and it seems to work fine. Refer #96
