### ISSUE TITLE
GetBhavcopy ver 3 :  In windows 7, .Net 4.6 version can't be installed.

### ISSUE THREAD

**Issue by sreenigki** [hemenkapadia/getbhavcopy#102]
GetBhavcopy ver 3 :  In windows 7, .Net 4.6 version can't be installed.  Please do needful

**Comment by pravinsmishra** [comment]
I have also same problem

**Comment by hemenkapadia** [comment]
.net 4.6.2 is supported on Windows 7 SP1. (https://www.microsoft.com/en-us/download/details.aspx?id=53344). You should update Windows 7 to SP1 first and then install .Net 4.6.2.

Moreover Windows 7 is getting EOL on 14 Jan 2020, so you should consider upgrading to Windows 10. https://support.microsoft.com/en-us/help/4057281/windows-7-support-will-end-on-january-14-2020
