### ISSUE TITLE
GetBhavcopy ver. 3a still not working for Windows 7

### ISSUE THREAD

**Issue by sreenigki** [hemenkapadia/getbhavcopy#103]
Hello Hemen Kabadia sir,
In Windown 7- 64bit,  DotNt  4.7 is not getting installing. Can you please suggest a way to side step this problem.

Regards

**Comment by hemenkapadia** [comment]
Please refer to comment in issue #102 . You will need Windows 7 SP1 or upgrade to Windows 10.
