### ISSUE TITLE
Getbhavcopy_3.0.0a does not work at all

### ISSUE THREAD

**Issue by chourpan** [hemenkapadia/getbhavcopy#108]
Getbhavcopy_3.0.0a does not work. start and end date filed are disable

**Comment by chourpan** [comment]
please do not put apps which does not work.

**Comment by ankush30** [comment]
NOT WORKING TODAY. I think its not working on weekends. Yesterday it was working

**Comment by chourpan** [comment]
Forget  it.. R  codes are available and able to down load historical bhav
copy from nse/bse website. Can be automated easily...

**Comment by neilazavedo** [comment]
Just tried... I could download the data right now ..

**Comment by neilazavedo** [comment]
chourpan you need to use version v3.0.0a currently I'm using build version 3.0.0.26182

**Comment by chourpan** [comment]
Thanks for advice..  but getbhavcopy can not be integrated with statistical
tool to build an analytical dashboard
Hence i am using R tool where it is very easy to build the dashboard.


Regards,
Pranjal

**Comment by ankush30** [comment]
its working now. But i agre the problem is there at time with NSE website. BTW pranjal can you guide me how to get r tool and bhavcopy. Also is there any tool which can help me download specific scrip over a date range..

**Comment by tusharbhardwaj1989** [comment]
so what should one do make this work? It's not downloading data.

**Comment by neilazavedo** [comment]
Data is updated on this thread : https://github.com/hemenkapadia/getbhavcopy/issues/107

**Comment by hemenkapadia** [comment]
@chourpan are you still facing the issue with the latest release 3.0.1a? Getbhavcopy is a general-purpose downloader that would download data as CSV. You can always load the CSV file in R to populate a data.table or data.frame

Strongly recommend using R data.table over data.frame. It may be initially difficult to learn but nothing matches its speed and performance. 

Disclaimer - data.table is developed by my colleague Matt D at H2O.ai.

**Comment by tusharbhardwaj1989** [comment]
Helo Hemen,

Sorry to disturb you, but this is still not working.

Best regards,
Tushar Bhardwaj
+91-987-177-51-51
