### ISSUE TITLE
While downloading error ""Error	The underlying connection was closed: An unexpected error occurred on a receive.""

### ISSUE THREAD

**Issue by niravshah74** [hemenkapadia/getbhavcopy#109]
While downloading error ""Error	The underlying connection was closed: An unexpected error occurred on a receive.""

**Comment by dsmgecj** [comment]
same problem faced by me. Pl. help

**Comment by kbg9** [comment]
Same Problem

**Comment by SANEVK** [comment]
same problem is being faced by me & I have already generated repository regarding this.
anyway thanks for generating it again.

**Comment by deep3542** [comment]
getbhav copy is giving the same error result and not downloading any data since past 14 days

**Comment by sanku74** [comment]
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for MIDCAP50

**Comment by sanku74** [comment]
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for MIDCAP50

**Comment by sanku74** [comment]
Not able to down load. Above msg is coming
please help me

**Comment by zubairra** [comment]
Same issue for me

**Comment by neilazavedo** [comment]
Data is only available for download daily from 12pm to about 8.30pm .. Good Day .. Some of us update the data after download in the other thread ..

**Comment by RS-NDIND** [comment]
> Data is only available for download daily from 12pm to about 8.30pm .. Good Day .. Some of us update the data after download in the other thread ..

As of today the download is not happening even at this time i.e 7.33pm IST

**Comment by neilazavedo** [comment]
Data uploaded by lakshmikanth in the other thread ....

**Comment by neilazavedo** [comment]
Data uploaded on this thread... Getbhavcopy V3.0.0a not wroking from 10-12-2019 for NSE server

**Comment by SANEVK** [comment]
Sir,

    NSE server giving problem from 5th December 2019

----- Mr. SANE V. K.

----- CONTACT NO. :- 9423002781

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a

**Comment by rkr0911** [comment]
It still gives the same error message even with the latest release. Can someone please help? In the meanwhile, can someone please send me the data from 21st Oct, as I was away and couldn't update the data from then.

**Comment by neilazavedo** [comment]
> 
> 
> It still gives the same error message even with the latest release. Can someone please help? In the meanwhile, can someone please send me the data from 21st Oct, as I was away and couldn't update the data from then.

[22nd oct to 3rd jan 2020.zip](https://github.com/hemenkapadia/getbhavcopy/files/4021922/22nd.oct.to.3rd.jan.2020.zip)

**Comment by rkr0911** [comment]
Thanks so much
