### ISSUE TITLE
Error	The underlying connection was closed: An unexpected error occurred on a receive. Message	Downloading index data for MIDCAP50

### ISSUE THREAD

**Issue by sanku74** [hemenkapadia/getbhavcopy#110]
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for MIDCAP50

**Comment by sanku74** [comment]
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for MIDCAP50

**Comment by neilazavedo** [comment]
Data is only available for download daily from 12pm to about 8.30pm .. Good Day .. Some of us update the data after download in the other thread ..

**Comment by neilazavedo** [comment]
Data gets uploaded on this thread .... Getbhavcopy V3.0.0a not wroking from 10-12-2019 for NSE server

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a
