### ISSUE TITLE
error downloading data 24.12.19

### ISSUE THREAD

**Issue by mehul-bosamia** [hemenkapadia/getbhavcopy#111]
tried several time for downloading data for 24.12.2019... following message its showing every time --
Message	*********  Downloading Data for 24-12-2019  *********
Message	Downloading NSE Equity Bhavcopy
Error	Error downloading NSE Equity Bhavcopy file
Error	The underlying connection was closed: An unexpected error occurred on a receive.

**Comment by neilazavedo** [comment]
Data is only available for download daily from 12pm to about 8.30pm .. Good Day ..

**Comment by saurabhmahajan** [comment]
I tried downloading before 8.30pm and getting the same error.

**Comment by neilazavedo** [comment]
Data is uploaded on this thread ... Getbhavcopy V3.0.0a not wroking from 10-12-2019 for NSE server

**Comment by mehul-bosamia** [comment]
Thank you. It shall be a useful info.
Thanks & regards Mehul Bosamiamobile - + 91 9320486468/9920692108

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a

**Comment by mehul-bosamia** [comment]
Thanks.
Thanks & regards Mehul Bosamiamobile - + 91 9320486468/9920692108
