### ISSUE TITLE
Attention Hemen Kapadia

### ISSUE THREAD

**Issue by lakshmikanthjc** [hemenkapadia/getbhavcopy#112]
Hi Hemen,

Looks like the download issue from getbhavcopy is really having some serious issues. We are facing this continuously from the thanksgiving holidays. Request you to look into this and help in correcting the problem. I have a feeling it is some hardware (server) issue at your end.

Regards,
Lakshmikanth

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a
