### ISSUE TITLE
possible solution to DATA NOT DOWNLOADING

### ISSUE THREAD

**Issue by sassy-ankit** [hemenkapadia/getbhavcopy#115]
nseindia.com is shifting from nseindia.com to beta.nseindia.com.
If u can modify download links, then this issue might be resolved.

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a

**Comment by vipuldamani** [comment]
Thanks HEMENBHAI.
aap no divas subha rahe. (hope u know gujrati - kapadia-base is surat)
