### ISSUE TITLE
Getvhavcopy not working.. please help   HemenKapadia

### ISSUE THREAD

**Issue by tarakbluru** [hemenkapadia/getbhavcopy#116]
Dear Hemen,
I am using getbhavcopy for some time now .. It is very much user friendly. Now that it is not working (or working inconsistently) tried a work around.. Not sure internally how you are downloading.. but following worked to download the zip file from here. https://www.nseindia.com/products/content/equities/equities/archieve_eq.htm  for example for 27 dec 2019, the link is 
https://www.nseindia.com/content/historical/EQUITIES/2019/DEC/cm27DEC2019bhav.csv.zip

To download this, I used curl binary from here: http://www.paehl.com/open_source/downloads/curl-release-static-ipv6-sspi-spnego-winssl_x64.7z  Unzip this into a folder.  In that folder, run the curl command given in the step2 below.

Steps:
1. get the argument that needs to be used with curl program from the explaination provided here. https://superuser.com/questions/1320212/firefox-download-from-command-line
2. ./curl "https://www.nseindia.com/content/historical/EQUITIES/2019/DEC/cm27DEC2019bhav.csv.zip" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "DNT: 1" -H "Connection: keep-alive" -H "Cookie: pointerfo=1; underlying1=M&M; instrument1=FUTSTK; optiontype1=-; expiry1=26DEC2019; strikeprice1=-; ak_bmsc=1BFCEBF71AB574361B1EF108FAE1ED446A332A0F73370000F754075EE3CB0C1C~plUhKPV90i4KBxUtnNZCJ3lfjuujmQvQKWTCA0J0AY6l2EUUvL4ncHVi4HTkptVttgOsUX96vaiUc302eXlx0WVCtF+b3TvDyHHFS2gNKXImdTjuHrvtie5A8i4HT6q+6Ec1kQh6bgN2HbiG77z9QECMDwkkwks5NBgWPXJpFkOIpp0EyfZem27QpMtMC/hb/BsaFBUK4wsx/FwwfbZ1eboHHR68B6Qpn/lUqLA5iScco=; bm_sv=72FDDC329CB01AA506A0911F9362C9E3~dOlcbeCMSCoNDGkID/l0ccrGGnyuLPQV7aUaWWmWNpucwf8JrBrrBfYbiIjdiZzkqFucyLrp/WK/3YoEu0WrnlmXFlQhy4VtTHoFeh1SJDgbjS7MF1DlVoVMba/HXGdko+dnshFfDS2YBip9z937m9IXTBYssmS3Vdumm9GjFqM=; bm_mi=8686EBD2CAB32B858A0664441CF48849~XDgmhftm2S9bFDuW3mWaW+sZyT+HwbRUI8LDHSV5qMOCv9jmy76UQ4wq9g3+FcvUmUr7JWEWuVmklqGGL2Dbwf2rG5P2vWp12tPW5cYiN/0r57C2GP0FwO20LLjoPStMOEnpBjDRVDhrXoLaVL9GU/SNV8KyQR/gjaImdOYR3GOsYpKjyo8pvGHWkKaG05wPZFCY0oY3r9benFr4yg06zlC4ShqvXq/4A1Nbk3K89Kr5KReAHCW8W24Vlr3NP9AMwB7PqEXn+MoS6vALHepDPEAbY4ZbVZ+FhvzYGGF9BFo=; NSE-TEST-1=1910513674.20480.0000; JSESSIONID=90395C45644623923222BD1AC5B35B15.tomcat2" -H "Upgrade-Insecure-Requests: 1" --output bhavcopy.zip

This downloads the bhavcopy in zipped format. 

getbhavcopy tool helps in reducing the work greatly.  If it could take a folder containing all these zipped bhavcopy and converts it into the usual format as a option; that would help a lot

Thank you and best regards,

**Comment by hemenkapadia** [comment]
ThanResolved in 3.0.1a
