### ISSUE TITLE
Timeout error 

### ISSUE THREAD

**Issue by shahss71** [hemenkapadia/getbhavcopy#117]
Dear sir, 
I think NSE changed the URL , getbhavcopy showing error "Error downloading  Data ",
I have changed the option available in NSEEQUITY tab , changed site address from www.nse-india.com to www.nseindia.com. Some data are now downloading but some gives error
Please do the needful.

![bhav](https://user-images.githubusercontent.com/59327728/71553141-e90d1680-2a2f-11ea-967b-99bb4eda5814.PNG)

**Comment by abhijitsingh27** [comment]
Hi, 
Have been getting this same error since almost 20 days. It got resolved for a day in between where i was able to download the pending days.
But this error has started again. Please help in resolving this asap!.

**Comment by neilazavedo** [comment]
everyday data is uploaded on this thread : https://github.com/hemenkapadia/getbhavcopy/issues/107 .. just comment or something there to get notifications via email when the data is uploaded ..

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a
