### ISSUE TITLE
getbhavcopy not working .

### ISSUE THREAD

**Issue by ajit1310** [hemenkapadia/getbhavcopy#118]
from last few days its not working , it worked on 12/29  all of sudden but now it not working .
I used one more software to build amibroker eod data for NSE and it worked . Not sure how the data in collected in this software , cash and future is straight forward but indices is tricky . In meanwhile you are fixing this issue can  you respond where is the error ?

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a
