### ISSUE TITLE
Getbhavcopy_3.0.1a has data download issue too.....

### ISSUE THREAD

**Issue by lakshmikanthjc** [hemenkapadia/getbhavcopy#122]
Getbhavcopy_3.0.1a like Getbhavcopy_3.0.0a also has data download issues, please look into it and resolve. Thank you.

**Comment by neilazavedo** [comment]
Hi lakshmikanth .. I just checked i was able to download the NSE data right now .. Wish you a very Happy New Year 2020..
[2019-12-31-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/4013681/2019-12-31-NSE-EQ.txt)

**Comment by hawaisanjay** [comment]
> Hi lakshmikanth .. I just checked i was able to download the NSE data right now .. Wish you a very Happy New Year 2020..
> [2019-12-31-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/4013681/2019-12-31-NSE-EQ.txt)

at what time did you download? because I am getting error now
![GB error](https://user-images.githubusercontent.com/55140666/71638128-801ade00-2c7d-11ea-8421-d557a724bbc6.jpg)

**Comment by neilazavedo** [comment]
I just check right now ... I can download the data..



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/01/20,
10:06:14 AM

**Comment by trade4mint** [comment]
Hi neilazavedo, 
I still cannot download with Getbhavcopy_3.0.1a, can you please provide me data file of NSE Cash with Header and open interest (which acts as deliverable volume in EQ) from 23rd Dec 2019 to 31st Dec 2019.

Thank you.

**Comment by neilazavedo** [comment]
Here it is trade4mint : 
[23Dec to 31st Dec 2019.zip](https://github.com/hemenkapadia/getbhavcopy/files/4013835/23Dec.to.31st.Dec.2019.zip)

**Comment by trade4mint** [comment]
> Here it is trade4mint :
> [23Dec to 31st Dec 2019.zip](https://github.com/hemenkapadia/getbhavcopy/files/4013835/23Dec.to.31st.Dec.2019.zip)

Thank you so much! :)

**Comment by Dhamnaik** [comment]
Message	*********  Starting Getbhavcopy  *********
Message	Downloading symbols for index NSENIFTY
Error	Error downloading symbols for index NSENIFTY from https://www.nseindia.com
Error	The operation has timed out

**Comment by neilazavedo** [comment]
Todays NSE Data : (Using Getbhavcopy 3.0.1a)
[2020-01-01-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/4014239/2020-01-01-NSE-EQ.txt)
[2020-01-01-NSE-EQ-with header+OI.txt](https://github.com/hemenkapadia/getbhavcopy/files/4014242/2020-01-01-NSE-EQ-with.header%2BOI.txt)

**Comment by lakshmikanthjc** [comment]
I was able to download the data today. After many days got a conviction that the application has got back to the state it was before the issues that it was facing for more than a month.
________________________________

**Comment by hemenkapadia** [comment]
Closed a confirmed it is working.

**Comment by lakshmikanthjc** [comment]
Thank you so much Hemen.

Rgds, Lakshmikanth
________________________________

**Comment by vivekmba05** [comment]
Pls upload 6th Jan 2020 data .txt file
