### ISSUE TITLE
Getbhavcopy_3.0.1a not working .

### ISSUE THREAD

**Issue by ajit1310** [hemenkapadia/getbhavcopy#123]
Getbhavcopy_3.0.1a  the latest version is not working . Just to give you some info,  similar package with other languages is working . I may the issue of giving full webaddress .

**Comment by kaly422000593** [comment]
getbhavcopy  is downloading some what ok around 8pm indian time for current day data. but on current day most of the indices giving errors before 8 pm . solution may be to reduce no of indices . downloading interrupted during some specific hrs. previous day data is downloading in specific time. so may be solution is to reduce no of indices ,keeping only main indices but thanx for ur effort. u can   intro donate option for debit card or wallet .

**Comment by neilazavedo** [comment]
Data is uploaded on this thread : https://github.com/hemenkapadia/getbhavcopy/issues/122

**Comment by hemenkapadia** [comment]
> 
> 
> Getbhavcopy_3.0.1a the latest version is not working . Just to give you some info, similar package with other languages is working . I may the issue of giving full webaddress .

Cannot help much with a simple statement that it is not working. Give logs and errors screenshot to help me understand the problem.

Based on my testing before release 3.0.1a was able to download data as expected for NSE and BSE,.

**Comment by neilazavedo** [comment]
> 
> 
> > Getbhavcopy_3.0.1a the latest version is not working . Just to give you some info, similar package with other languages is working . I may the issue of giving full webaddress .
> 
> Cannot help much with a simple statement that it is not working. Give logs and errors screenshot to help me understand the problem.
> 
> Based on my testing before release 3.0.1a was able to download data as expected for NSE and BSE,.

Hi Hemen .. from where can I retrieve the log file ..

**Comment by b4bhavinshah** [comment]
![ERR](https://user-images.githubusercontent.com/57207877/71650919-90938d00-2d3f-11ea-94ed-99dbcf709498.jpg)

**Comment by b4bhavinshah** [comment]
[log.txt](https://github.com/hemenkapadia/getbhavcopy/files/4014876/log.txt)

**Comment by neilazavedo** [comment]
ok got it... I will send it to you ... 

![getbhav301a](https://user-images.githubusercontent.com/58835329/71650961-f97b0500-2d3f-11ea-9c38-682a6499e8c3.jpg)

Log File 
[301a-log.txt](https://github.com/hemenkapadia/getbhavcopy/files/4014877/301a-log.txt)

**Comment by shreezen** [comment]
MD5 sumdoes not match. You have given MD5 checksum for 3.0.0a.zip. 
File to download is 3.0.1a.zip

**Comment by ajit1310** [comment]
> > Getbhavcopy_3.0.1a the latest version is not working . Just to give you some info, similar package with other languages is working . I may the issue of giving full webaddress .
> 
> Cannot help much with a simple statement that it is not working. Give logs and errors screenshot to help me understand the problem.
> 
> Based on my testing before release 3.0.1a was able to download data as expected for NSE and BSE,.


see below ,  as the files are overwritten every time , the getbhavcopy should work all the time . As NSE is not stopping from EOD data mining , it should work at any time in a day .
![image](https://user-images.githubusercontent.com/58735112/71722522-210cc300-2e4f-11ea-953b-4502c9f641be.png)

**Comment by neilazavedo** [comment]
Please check this thread https://github.com/hemenkapadia/getbhavcopy/issues/125 for a possible solution ...

**Comment by shreezen** [comment]
Thanks. It works now!!
