### ISSUE TITLE
Similar Issue like 3.0.0

### ISSUE THREAD

**Issue by Chhirag** [hemenkapadia/getbhavcopy#125]
Dear Hemen, the new 3.0.1a version is also throwing out same error as it was in 3.0.0a. I got error in NSE Cash data as I downloaded that only. I am attaching the screenshots & log file so it will be easier for you to figure out the issue. I am using it on Windows 10, and it is located in documents folder. Before Dec, it was working absolutely fine on same device & location. 

Thank You!
[log.txt](https://github.com/hemenkapadia/getbhavcopy/files/4014938/log.txt)
![IMG_20200102_103945_536](https://user-images.githubusercontent.com/25126528/71652719-79f43280-2d4d-11ea-8dee-138536b81ba1.jpg)
![IMG_20200102_103952_014](https://user-images.githubusercontent.com/25126528/71652720-79f43280-2d4d-11ea-9257-889d93fa1ae6.jpg)
![IMG_20200102_103956_039](https://user-images.githubusercontent.com/25126528/71652721-7a8cc900-2d4d-11ea-829e-8b4925a5f07f.jpg)
![IMG_20200102_103957_954](https://user-images.githubusercontent.com/25126528/71652722-7a8cc900-2d4d-11ea-8de9-29d9fc93a2ad.jpg)

**Comment by hemenkapadia** [comment]
While I do agree that you are facing the error I am not facing any error while downloading the data for NSE or BSE. Unless I can reproduce the issue there is not much I can do. 

Below is a gif image showing version 3.0.1a downloading NSE and BSE data without any issue.

![Install_3](https://user-images.githubusercontent.com/9943123/71657869-8600d580-2cf6-11ea-8134-510761b3962e.gif)

**Comment by Chhirag** [comment]
Hemen, I got the solution. If we uncheck "Output data will contain Indices volume...." it starts working flawlessly. I highlighted this in screenshot, and I hope this will help other people also who are getting similar issue. 

And lastly, can't thank you enough Hemen for your helpfulness! Have a wonderful time ahead!
![2020-01-03_9-22-16](https://user-images.githubusercontent.com/25126528/71708320-7b3d6200-2e16-11ea-8f0b-d3f9eee30fc5.jpg)

**Comment by b4bhavinshah** [comment]
Thanks Chhirag!!! it works fine now.

**Comment by madhumailbox** [comment]
Message	*********  Starting Getbhavcopy  *********
Message	*********  Downloading Data for 03-01-2020  *********
Message	Downloading NSE Equity Bhavcopy
Error	Error downloading NSE Equity Bhavcopy file
Error	The operation has timed out
Message	Downloading index data for NSENIFTY

**Comment by madhumailbox** [comment]
Message	*********  Starting Getbhavcopy  *********
Message	*********  Downloading Data for 03-01-2020  *********
Message	Downloading NSE Equity Bhavcopy
Error	Error downloading NSE Equity Bhavcopy file
Error	The operation has timed out
Message	Downloading index data for NSENIFTY
Error	Error downloading Index Data for NSENIFTY
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for NIFTYJUNIOR
Error	Error downloading Index Data for NIFTYJUNIOR
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for NIFTYMIDCAPLIQ15
Error	Error downloading Index Data for NIFTYMIDCAPLIQ15
Error	The underlying connection was closed: An unexpected error occurred on a receive.
Message	Downloading index data for NSE100

**Comment by neilazavedo** [comment]
madhumailbox did you try what Chhirag has suggested?

**Comment by Agrawalritesh** [comment]
Still can not download data. Can anyone pl upload NSECASH file for 02/01/2020 and 03/01/2020

**Comment by madhumailbox** [comment]
@ neilazavedo   the check box is already unchecked for me...  Thanks for your revert!!  Support appreciated..  Yesterday i was not able to download 3rd jan data, now its working..
Thank a TON hemen sir for your application and support

**Comment by ktk44** [comment]
new version not working. the data is downloading but the file is not being created.
![bhavcopy error](https://user-images.githubusercontent.com/59501704/71765441-d22c5f80-2f1a-11ea-9c11-8f1f0d4a330d.jpg)

**Comment by madhumailbox** [comment]
bse is working , nse is not...

Message	*********  Starting Getbhavcopy  *********
Message	*********  Downloading Data for 03-01-2020  *********
Message	Downloading NSE Equity Bhavcopy
Error	Could not extract NSE zip file.
Error	Cannot find central directory
Message	Downloading index data for NSENIFTY
Error	Error downloading Index Data for NSENIFTY
Error	The operation has timed out
Message	Downloading index data for NIFTYJUNIOR

**Comment by madhumailbox** [comment]
now downloading happens for NSE but no file is created  , but bse is ok

Message	Downloading index data for NIFTY-GS-10YR-CLN
Message	Downloading index data for NIFTY-GS-11-15YR
Message	Downloading index data for NIFTY-GS-15YRPLUS
Message	Downloading index data for VIX
Message	Processing downloaded data
Error	NSE Processor cannot open temporary bhavcopy file
Error	Could not find file 'C:\Users\Madhu\Desktop\temp\NSEbhav.gbc'.
Message	Downloading NSE Futures Bhavcopy
Error	Could not extract NSE futures bhavcopy zip file.
Error	Cannot find central directory
Message	Downloading BSE Equity Bhavcopy

**Comment by tjagad** [comment]
NSE has switched to the new website by default from 4th Jan, 2020. I believe that is causing the issue. @hemenkapadia could you please check the URL for the bhavcopy zip file which is failing after the latest update as well.

Also any clue why the following messages appear in the logs ?

```
Message	Downloading index data for NIFTYSMALLCAP250
Error	NSE server did not return data for index NIFTYSMALLCAP250
Message	Downloading index data for NIFTYSMALLCAP50
Error	NSE server did not return data for index NIFTYSMALLCAP50
Message	Downloading index data for NIFTY200QUALITY30
Error	NSE server did not return data for index NIFTY200QUALITY30
```

**Comment by arvindeept** [comment]
> Hemen, I got the solution. If we uncheck "Output data will contain Indices volume...." it starts working flawlessly. I highlighted this in screenshot, and I hope this will help other people also who are getting similar issue.
> 
> And lastly, can't thank you enough Hemen for your helpfulness! Have a wonderful time ahead!
> ![2020-01-03_9-22-16](https://user-images.githubusercontent.com/25126528/71708320-7b3d6200-2e16-11ea-8f0b-d3f9eee30fc5.jpg)

Hi chirag. Is it still working for you?

**Comment by Chhirag** [comment]
> > Hemen, I got the solution. If we uncheck "Output data will contain Indices volume...." it starts working flawlessly. I highlighted this in screenshot, and I hope this will help other people also who are getting similar issue.
> > And lastly, can't thank you enough Hemen for your helpfulness! Have a wonderful time ahead!
> > ![2020-01-03_9-22-16](https://user-images.githubusercontent.com/25126528/71708320-7b3d6200-2e16-11ea-8f0b-d3f9eee30fc5.jpg)
> 
> Hi chirag. Is it still working for you?

It was working till afternoon of Jan 03, but later NSE INDIA changed the URL for the bhavcopy zip file which it downloads & process. So it stopped working for me as well. This is different issue from the earlier one but I think a small change in URL can fix GBC as older system is still available at this link- https://www1.nseindia.com/products/content/equities/equities/archieve_eq.htm

**Comment by arvindeept** [comment]
Ok, thanks bro.

**Comment by hemenkapadia** [comment]
> 
> 
> Hemen, I got the solution. If we uncheck "Output data will contain Indices volume...." it starts working flawlessly. I highlighted this in screenshot, and I hope this will help other people also who are getting similar issue.
> 
> And lastly, can't thank you enough Hemen for your helpfulness! Have a wonderful time ahead!
> ![2020-01-03_9-22-16](https://user-images.githubusercontent.com/25126528/71708320-7b3d6200-2e16-11ea-8f0b-d3f9eee30fc5.jpg)

Thanks @Chhirag , Greatly appreciate your research and contribution to the community.

**Comment by Vijay-KK** [comment]
Hi all,

Just running the software as administrator, it starts working...please try...
