### ISSUE TITLE
crude solution .

### ISSUE THREAD

**Issue by ajit1310** [hemenkapadia/getbhavcopy#130]
Hemen ,
For the time being ,  add one more radio button as shown in the screenshot ,  the new radio button is for selection of webaddress  "https://www1.nseindia" , alternatively you can replace  "nse-india.com " with "https://www1.nseindia".

Thanks,
Ajit 

![image](https://user-images.githubusercontent.com/58735112/71820261-a218c400-30b4-11ea-9df7-a5531f7883d6.png)

**Comment by hbinmadi** [comment]
thanks ajit
can u please tell me which editor or ide we can use to do so

**Comment by ajit1310** [comment]
> thanks ajit
> can u please tell me which editor or ide we can use to do so

This is for Hemen to do , it has to be coded inside the program. So if you know in which language the getbhavcopy is coded you can go to the frame and change it , it will be available on your machine only  . But as Hemen owns this and he maintain all the version and know where to code , he can do it .

**Comment by hemenkapadia** [comment]
Thanks - will implement

**Comment by hemenkapadia** [comment]
This should work for now. I was not able to find a location where the daily bhavcopy.zip file is available on the new website. If that is not available then probably EOL for Getbhavcopy then...

**Comment by arvindeept** [comment]
Here it is......https://www1.nseindia.com/products/content/equities/equities/archieve_eq.htm

**Comment by arvindeept** [comment]
From this link, we are directed to the above link......https://www.nseindia.com/all-reports

**Comment by hemenkapadia** [comment]
Fixed in 3.0.2a

**Comment by Chirag9725** [comment]
Message	*********  Downloading Data for 03-01-2020  *********
Message	Downloading NSE Equity Bhavcopy
Error	Could not extract NSE zip file.
Error	Cannot find central directory
Message	Downloading index data for NSENIFTY


Dear Sir Still Above issue is there where i can't able to download data 

If any one having file from 8th Jan 9th Jan 10th Jan
