### ISSUE TITLE
 Error	Error downloading Index Data for NSENIFTY

### ISSUE THREAD

**Issue by sanku74** [hemenkapadia/getbhavcopy#131]
Error	Error downloading Index Data for NSENIFTY
Error	The underlying connection was closed: The connection was closed unexpectedly.
Message	Downloading index data for NIFTYJUNIOR
Error	Error downloading Index Data for NIFTYJUNIOR
Error	The underlying connection was closed: The connection was closed unexpectedly.
Message	Downloading index data for NIFTYMIDCAPLIQ15

**Comment by sanku74** [comment]
Please help me as I am not able to download through Getbhvcopy

**Comment by neilazavedo** [comment]
Data is uploaded here : https://github.com/hemenkapadia/getbhavcopy/issues/127

**Comment by hemenkapadia** [comment]
Closed - duplicate of #127
