### ISSUE TITLE
Error	Could not extract NSE zip file.

### ISSUE THREAD

**Issue by tusharmdave** [hemenkapadia/getbhavcopy#133]
01/07/2020 08:21:05	Message	*********  Starting Getbhavcopy  *********
01/07/2020 08:21:14	Message	*********  Downloading Data for 06-01-2020  *********
01/07/2020 08:21:14	Message	Downloading NSE Equity Bhavcopy
01/07/2020 08:21:15	Error	Could not extract NSE zip file.
01/07/2020 08:21:15	Error	Cannot find central directory
01/07/2020 08:21:15	Message	Downloading index data for NSENIFTY

**Comment by vipuldamani** [comment]
yews same issue.
with both NSE link.

**Comment by nk10garg** [comment]
same issue here
![error](https://user-images.githubusercontent.com/59593183/71869649-d209ab00-3138-11ea-8529-7436587c6fb8.png)

**Comment by hemenkapadia** [comment]
closed duplicate of #127
