### ISSUE TITLE
MD5 Sum of Getbhavcopy.exe Does Not Match

### ISSUE THREAD

**Issue by rajendraghelani** [hemenkapadia/getbhavcopy#134]
MD5 Sum of Getbhavcopy.exe & MD5 Sum of Getbhavcopy_3.0.0a.zip does not match with uploaded file.

**Comment by hemenkapadia** [comment]
Thanks for bringing this to my notice. Copy pasted from 3.0.0a and missed updating it during the release. I have now updated the md5 sums
