### ISSUE TITLE
Intermittent working

### ISSUE THREAD

**Issue by shivakn2003** [hemenkapadia/getbhavcopy#141]
Hemant
Getbhavcopy works but intermittently. Not able to pinpoint under what circumstances the app doesn't work. I hv tried installing from scratch, different folder.. this is the message I get more often: 
01/11/2020 11:18:39	Message	*********  Starting Getbhavcopy  *********
01/11/2020 11:18:46	Message	Downloading symbols for index NSENIFTY
01/11/2020 11:19:54	Error	Error downloading symbols for index NSENIFTY from https://www1.nseindia.com
01/11/2020 11:19:54	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:19:54	Message	Downloading symbols for index NIFTYJUNIOR
01/11/2020 11:20:55	Error	Error downloading symbols for index NIFTYJUNIOR from https://www1.nseindia.com
01/11/2020 11:20:55	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:20:55	Message	Downloading symbols for index NSE100
01/11/2020 11:21:34	Error	Error downloading symbols for index NSE100 from https://www1.nseindia.com
01/11/2020 11:21:34	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:21:34	Message	Downloading symbols for index NSE500
01/11/2020 11:22:13	Error	Error downloading symbols for index NSE500 from https://www1.nseindia.com
01/11/2020 11:22:13	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:22:13	Message	Downloading symbols for index NSEMIDCAP150
01/11/2020 11:22:51	Error	Error downloading symbols for index NSEMIDCAP150 from https://www1.nseindia.com
01/11/2020 11:22:51	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:22:51	Message	Downloading symbols for index MIDCAP50
01/11/2020 11:23:30	Error	Error downloading symbols for index MIDCAP50 from https://www1.nseindia.com
01/11/2020 11:23:30	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:23:30	Message	Downloading symbols for index NSEMIDCAP
01/11/2020 11:24:08	Error	Error downloading symbols for index NSEMIDCAP from https://www1.nseindia.com
01/11/2020 11:24:08	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:24:08	Message	Downloading symbols for index NIFTYSMALLCAP250
01/11/2020 11:24:47	Error	Error downloading symbols for index NIFTYSMALLCAP250 from https://www1.nseindia.com
01/11/2020 11:24:47	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:24:47	Message	Downloading symbols for index NIFTYSMALLCAP50
01/11/2020 11:25:25	Error	Error downloading symbols for index NIFTYSMALLCAP50 from https://www1.nseindia.com
01/11/2020 11:25:26	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:25:26	Message	Downloading symbols for index NSESMLCAP100
01/11/2020 11:26:04	Error	Error downloading symbols for index NSESMLCAP100 from https://www1.nseindia.com
01/11/2020 11:26:04	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:26:04	Message	Downloading symbols for index NIFTYLARGEMIDCAP250
01/11/2020 11:26:43	Error	Error downloading symbols for index NIFTYLARGEMIDCAP250 from https://www1.nseindia.com
01/11/2020 11:26:43	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:26:43	Message	Downloading symbols for index NIFTYMIDSMALLCAP400
01/11/2020 11:27:21	Error	Error downloading symbols for index NIFTYMIDSMALLCAP400 from https://www1.nseindia.com
01/11/2020 11:27:21	Error	The underlying connection was closed: An unexpected error occurred on a receive.
01/11/2020 11:27:21	Message	Downloading symbols for index BANKNIFTY
01/11/2020 11:30:14	Message	*********  Starting Getbhavcopy  *********

**Comment by hemenkapadia** [comment]
This is an NSE Server issue. This cannot be fixed in Getbhavcopy. I think you should download files at a time when the load on server is less.
