### ISSUE TITLE
[ E R R O R] Could not extract NSE ZIP file

### ISSUE THREAD

**Issue by raghavmehta86** [hemenkapadia/getbhavcopy#143]
Greetings Hemen

First up, thanks for making this tool, I have been using it for a long time now, I really appreciate the time you have put into making this tool. 

I have upgraded to the latest version 3.0.1a on 1st Jan 2020. It was working fine up until 5th Jan 2020. Since 6th Jan it has stopped working, let me show you the logs I have collected so far. 
```
]L O G S[ Version 3.0.1a
------------------------------------------------------------------------------------------------------------
01/06/2020 18:09:23	Message	*********  Starting Getbhavcopy  *********
01/06/2020 18:09:28	Message	*********  Downloading Data for 06-01-2020  *********
01/06/2020 18:09:28	Message	Downloading NSE Equity Bhavcopy
01/06/2020 18:09:33	Error	Could not extract NSE zip file.
01/06/2020 18:09:33	Error	Cannot find central directory
01/06/2020 18:09:33	Message	Downloading index data for NSENIFTY
01/11/2020 02:36:45	Error	Error communicating with Google Analytics.
01/11/2020 02:36:45	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 02:36:46	Message	*********  Starting Getbhavcopy  *********
01/11/2020 02:37:00	Error	Error communicating with Google Analytics.
01/11/2020 02:37:00	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 02:37:01	Error	Error communicating with Google Analytics.
01/11/2020 02:37:01	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 02:37:01	Message	Version check using Github API failed.
01/11/2020 02:37:01	Message	Checking with Raw Github content
01/11/2020 02:37:02	Message	*********  Downloading Data for 06-01-2020  *********
01/11/2020 02:37:02	Message	Downloading NSE Equity Bhavcopy
01/11/2020 02:37:04	Error	Error communicating with Google Analytics.
01/11/2020 02:37:04	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 02:37:04	Error	Could not extract NSE zip file.
01/11/2020 02:37:04	Error	Cannot find central directory
01/11/2020 02:37:04	Message	Downloading index data for NSENIFTY
01/11/2020 19:46:43	Error	Error communicating with Google Analytics.
01/11/2020 19:46:43	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 19:46:43	Message	*********  Starting Getbhavcopy  *********
01/11/2020 19:51:56	Error	Error communicating with Google Analytics.
01/11/2020 19:51:56	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 19:51:57	Error	Error communicating with Google Analytics.
01/11/2020 19:51:57	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 19:51:57	Message	Version check using Github API failed.
01/11/2020 19:51:57	Message	Checking with Raw Github content
01/11/2020 19:51:59	Message	*********  Downloading Data for 06-01-2020  *********
01/11/2020 19:51:59	Message	Downloading NSE Equity Bhavcopy
01/11/2020 19:52:01	Error	Error communicating with Google Analytics.
01/11/2020 19:52:01	Error	The remote server returned an error: (403) Forbidden.
01/11/2020 19:52:01	Error	Could not extract NSE zip file.
01/11/2020 19:52:01	Error	Cannot find central directory
01/11/2020 19:52:01	Message	Downloading index data for NSENIFTY
01/12/2020 13:02:29	Error	Error communicating with Google Analytics.
01/12/2020 13:02:29	Error	The remote server returned an error: (403) Forbidden.
01/12/2020 13:02:29	Message	*********  Starting Getbhavcopy  *********
01/12/2020 13:13:05	Error	Error communicating with Google Analytics.
01/12/2020 13:13:05	Error	The remote name could not be resolved: 'www.google-analytics.com'
01/12/2020 13:13:05	Message	*********  Starting Getbhavcopy  *********
01/12/2020 13:15:40	Error	Error communicating with Google Analytics.
01/12/2020 13:15:40	Error	The remote server returned an error: (403) Forbidden.
01/12/2020 13:15:40	Message	*********  Starting Getbhavcopy  *********
01/12/2020 13:21:28	Error	Error communicating with Google Analytics.
01/12/2020 13:21:28	Error	The remote server returned an error: (403) Forbidden.
01/12/2020 13:21:28	Message	*********  Starting Getbhavcopy  *********
01/12/2020 14:22:24	Error	Error communicating with Google Analytics.
01/12/2020 14:22:24	Error	The remote server returned an error: (403) Forbidden.
01/12/2020 14:22:24	Message	*********  Starting Getbhavcopy  *********
-----------------------------------------------------------------------------------------------------------
```
Upgraded to 3.2.a on 12 Jan and when I open the tool, it gives me an error "Error communicating with Google analytics " and crashes. 

I am using Windows 10, dot net framework is compatible. 
No entries made in host file. 
I have disabled anti-virus and firewalls to see if they are causing an issue. 
The folder where data has downloaded has right authorization, there is enough space on the disk. 
No changes made in registeries. 

I am not sure what else can I do here. 

Please help. 

Regards
Raghav Mehta

**Comment by neilazavedo** [comment]
raghavmehta86 .. Please refer and check if you are doing everything right : http://www.getbhavcopy.com/blog/2017/02/13/Installing-Getbhavcopy.html

Latest version : https://github.com/hemenkapadia/getbhavcopy/releases

**Comment by raghavmehta86** [comment]
Neil I have been using this tool for over a year now, I have followed all the things mentioned in the document. 

Please see the screenshot , this happens as soon as I open version 3.0.2.a. 

![Annotation 2020-01-12 163037](https://user-images.githubusercontent.com/59791418/72217788-edb9ea80-3558-11ea-854f-681284b37d1c.png)

**Comment by neilazavedo** [comment]
Well maybe you can try this suggested to me by Hemen in the other thread

You can enable Debug mode in Getbhavcopy and share the log. Additionally, the log file has the BSE URLs it is trying to connect to. You can try opening them in your browser. Also check if your browser has any proxy configured.

    Browse to the directory where you have getbhavcopy.exe file.
    Delete the log folder existing in that directory.
    Start the command prompt , Start >> run >> cmd
    Change to the directory where you have getbhavcopy.exe
    In that directory start getbhavcopy as 'getbhavcopy.exe debugon'
    Try to download the data as you do normally.
    You will see the log directory will be recreated, with a log file inside it.
    Share the contents of the log file on the github issue.

You can refer to it here : https://github.com/hemenkapadia/getbhavcopy/issues/104

**Comment by raghavmehta86** [comment]
Thanks for the reply Neil. 

As I mentioned above, tool crashes as soon as I open it, please see the gif I made. 

It won't really generate any logs until the call is made to the server, will it? 
![Bhavcopy](https://user-images.githubusercontent.com/59791418/72222506-37bbc400-358b-11ea-8afb-fdb1933fc12d.gif)

**Comment by madhanji** [comment]
hi Thanks Hemen ....

Really This time you had fast updation to 3.0.2a...
works well...

**Comment by raghavmehta86** [comment]
Okay, so if any one else faces this problem, try switching your network, this was a problem from my ISPs side, I used a different network today and it worked flawlessly. 

Cheers.

**Comment by vantive** [comment]
for me @raghavmehta86 comment helped. it was a problem with my isp which was blocking the site. when I switched the network then the nse data downloaded properly.
