### ISSUE TITLE
Bhav Copy of Budget Session

### ISSUE THREAD

**Issue by rajendraghelani** [hemenkapadia/getbhavcopy#149]
There was a special live session on Saturday the 01/02/2020 on NSE & BSE on account of Union Budget 2020. Due to a scheduled weekly holiday on  Saturday, Bhav Copy cannot be downloaded. Kindly provide a solution.

**Comment by niravshah74** [comment]
yes ...i also need ...thank you...

**Comment by codebraker** [comment]
Did you get a solution?

**Comment by codebraker** [comment]
> There was a special live session on Saturday the 01/02/2020 on NSE & BSE on account of Union Budget 2020. Due to a scheduled weekly holiday on Saturday, Bhav Copy cannot be downloaded. Kindly provide a solution.

Did you get a solution?

**Comment by rajendraghelani** [comment]
Yes! I got the solution.

Thanks A Lot.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by rajendraghelani** [comment]
Yes! I got the solution.
Thanks A Lot.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by rajendraghelani** [comment]
Yes! I got the solution.
Thanks A Lot.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by niravshah74** [comment]
Yes Today I get the solution......Thanks a lot..
