### ISSUE TITLE
Does it work in Windows-10? 

### ISSUE THREAD

**Issue by giteshs999** [hemenkapadia/getbhavcopy#15]
It shows following message.

![image](https://user-images.githubusercontent.com/21261127/35547190-96a68f2e-059d-11e8-86f7-1ce6f158d4a3.png)

I cannot even change dates. It remains on this message forever.

I tried changing compatibility settings to windows-7 or windows-XP-SP3, but no avail.

**Comment by hemenkapadia** [comment]
Hi @giteshs999 ,

Yes it definitely works on Windows 10. I develop it on Windows 10.

Notice the Options button, can you try setting the options first?

**Comment by giteshs999** [comment]
Hello Hemen, 

It does work after setting options. I guess I missed the same. 

Let me now try importing into metastock.

Thanks.

**Comment by hemenkapadia** [comment]
Closing issue. Resolved.
