### ISSUE TITLE
Bhavcopy data for 1st Feb 2020 - Budget day

### ISSUE THREAD

**Issue by codebraker** [hemenkapadia/getbhavcopy#151]
How can one download bhavdcopy data for Saturday 1st Feb 2020 i.e. Budget day.

**Comment by neilazavedo** [comment]
codebraker .... get into options of getbhavcopy and untick ignore weekend and save.. You should be able to download the data.

**Comment by codebraker** [comment]
> codebraker .... get into options of getbhavcopy and untick ignore weekend and save.. You should be able to download the data.

WoW... how did I miss this! Thanks a ton for the hint ;)
