### ISSUE TITLE
Feature provision to download BhavCopy only for selected symbols

### ISSUE THREAD

**Issue by aarvee53** [hemenkapadia/getbhavcopy#152]
I feel an option to download the BhavCopy for selected symbols ( can be uploaded through Excel / Txt ) instead of all symbols would be very useful and also help us focus on the symbols that we want to focus.  Alternatively this can also be by groups like Nifty50, Nifty100, Nifty Midcap100 etc.

**Comment by hemenkapadia** [comment]
Getbhavcopy downloads the entire bhavcopy file for all symbols in one shot. It is a single download and is very fast. I don't think providing symbol-based download makes sense, as I will have to download the file for all symbols as is.
