### ISSUE TITLE
for  WIN7  Service pack1 will  support .Net4.6 ?   ( WIN7 does not release SP2  you suggest ) for  Getbhavcopy  Ver 3.0.0 ?

### ISSUE THREAD

**Issue by PatelJS** [hemenkapadia/getbhavcopy#154]
Dear Hemen Sir,

You suggest for Getbhavcopy Ver 3.0.0

for   OS WIN7 Service Pack2    will support updating .Net 4.0  to .Net 4.6
BUT  WIN7  does not release Service Pack2.  it will  run on WIN7 Service Pack1 ? 
Sir ?

**Comment by hemenkapadia** [comment]
It may not run if .net 4.6 cannot be installed. Windows 7 is a very old system and very difficult for me to keep supporting old versions.
