### ISSUE TITLE
Server Unavailable error

### ISSUE THREAD

**Issue by morphu77** [hemenkapadia/getbhavcopy#186]
Trying to download today's bhavcopy , getting an error "Server not available " . log extract below .let me know if more details are needed

Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-4-8YR
Error	Error downloading Index Data for NIFTY-GS-4-8YR
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-8-13YR
Error	Error downloading Index Data for NIFTY-GS-8-13YR
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-10YR
Error	Error downloading Index Data for NIFTY-GS-10YR
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-10YR-CLN
Error	Error downloading Index Data for NIFTY-GS-10YR-CLN
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-11-15YR
Error	Error downloading Index Data for NIFTY-GS-11-15YR
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-15YRPLUS
Error	Error downloading Index Data for NIFTY-GS-15YRPLUS

**Comment by timaraws** [comment]
getting this same error...please help asap....

**Comment by morphu77** [comment]
WORKING NOw seems like a transient connectivity issue at NSE end

**Comment by timaraws** [comment]
> 
> 
> WORKING NOw seems like a transient connectivity issue at NSE end

still not working for me.... :(

**Comment by timaraws** [comment]
could you please me the txt file for today @ amitswar@gmail.com....appreciate your help...

**Comment by timaraws** [comment]
Else you could upload the file here.....
