### ISSUE TITLE
Error downloading NSE Equity Bhavcopy.

### ISSUE THREAD

**Issue by sashivijaya** [hemenkapadia/getbhavcopy#189]
Hi admin,
I am unable to download the Bhavcopy from NSE.

Enclosed Error message for your reference.

Kindly resolve the issue and helpful to us.

Thanks and Best Regards
G.Sashi

Message	*********  Starting Getbhavcopy  *********
Message	*********  Downloading Data for 08-03-2021  *********
Message	Downloading NSE Equity Bhavcopy
Error	Error downloading NSE Equity Bhavcopy file
Error	The remote server returned an error: (503) Server Unavailable.

**Comment by sandeep1971** [comment]
Same error and cannot access direct also from www1.nseindia.com

**Comment by touchofevil-dev** [comment]
Duplicate of #187

**Comment by sashivijaya** [comment]
Hi Admin,

Now Getbhavcopy working properly.

**Comment by sashivijaya** [comment]
Hi Admin,
Now Getbhavcopy server problem resolved and working properly.







> Hi admin,
> I am unable to download the Bhavcopy from NSE.
> 
> Enclosed Error message for your reference.
> 
> Kindly resolve the issue and helpful to us.
> 
> Thanks and Best Regards
> G.Sashi
> 
> Message ********* Starting Getbhavcopy *********
> Message ********* Downloading Data for 08-03-2021 *********
> Message Downloading NSE Equity Bhavcopy
> Error Error downloading NSE Equity Bhavcopy file
> Error The remote server returned an error: (503) Server Unavailable.
