### ISSUE TITLE
Unable to Download EOD Data - Error 503

### ISSUE THREAD

**Issue by arunbssr** [hemenkapadia/getbhavcopy#190]
Hello Sir,

Cant able to download the EOD data for 08 March 2021. Getting error: The remote server returned an error: (503) Server Unavailable

Kindly resolve. 

Log Report for your information.

03/09/2021 06:05:39	Message	*********  Starting Getbhavcopy  *********
03/09/2021 06:05:50	Message	*********  Downloading Data for 08-03-2021  *********
03/09/2021 06:05:50	Message	Downloading NSE Equity Bhavcopy
03/09/2021 06:05:51	Error	Error downloading NSE Equity Bhavcopy file
03/09/2021 06:05:51	Error	The remote server returned an error: (503) Server Unavailable.
03/09/2021 06:05:52	Message	Downloading index data for NSENIFTY
03/09/2021 06:05:53	Error	Error downloading Index Data for NSENIFTY
03/09/2021 06:05:53	Error	The remote server returned an error: (503) Server Unavailable.
03/09/2021 06:05:53	Message	Downloading index data for NIFTYJUNIOR
03/09/2021 06:05:53	Error	Error downloading Index Data for NIFTYJUNIOR
03/09/2021 06:05:53	Error	The remote server returned an error: (503) Server Unavailable.
03/09/2021 06:05:53	Message	Downloading index data for NIFTYMIDCAPLIQ15
03/09/2021 06:05:54	Error	Error downloading Index Data for NIFTYMIDCAPLIQ15
03/09/2021 06:05:54	Error	The remote server returned an error: (503) Server Unavailable.

**Comment by sandeep1971** [comment]
Same error and cannot access direct also from www1.nseindia.com

**Comment by touchofevil-dev** [comment]
Duplicate of #187

**Comment by iiflvalsad** [comment]
Since Yesterday facing same Problem : Error The remote server returned an error: (503) Server Unavailable.

Also request you to help me , How I can download NSE eod data for Trade to trade segment stocks .  Getbhavcopy not downloading it in my computer, while my friend is getting all datas

**Comment by sandeep1971** [comment]
Open bhavcopy in excel and Replace  BE to EQ

**Comment by sairajparayath** [comment]
> Open bhavcopy in excel and Replace  BE to EQ 

Hi , can you please elaborate ? Thanks _

**Comment by sandeep1971** [comment]
For trade to trade scrips , conver BE segment to EQ

**Comment by iiflvalsad** [comment]
> Open bhavcopy in excel and Replace BE to EQ

sir thanks for reply, but its pending since 2020 , I will be thanksfull if you can send files to my email : iiflvalsad@gmail.com

**Comment by iiflvalsad** [comment]
> For trade to trade scrips , conver BE segment to EQ

How to covert sir, in Text no Eq or BE !!
Example of text :Bhavcopy 
20MICRONS,20210301,36.9,37.6,36.55,37.35,126886
21STCENMGM,20210301,11.95,11.95,11.95,11.95,2571
3IINFOTECH,20210301,6.3,6.45,6.05,6.45,7851294
3MINDIA,20210301,23175,24500,23174.9,24148.65,17103
3PLAND,20210301,9.15,9.95,9.15,9.55,13330
5PAISA,20210301,261.9,272.9,260.5,263.85,40788

**Comment by morphu77** [comment]
Getting the error server not available .No responses from the author , guess this software is no longer supported which is a pity as it is so widely used now.

Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-10YR-CLN
Error	Error downloading Index Data for NIFTY-GS-10YR-CLN
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-11-15YR
Error	Error downloading Index Data for NIFTY-GS-11-15YR
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for NIFTY-GS-15YRPLUS
Error	Error downloading Index Data for NIFTY-GS-15YRPLUS
Error	The remote server returned an error: (503) Server Unavailable.
Message	Downloading index data for VIX
Error	Error downloading Index Data for VIX
Error	The remote server returned an error: (503) Server Unavailable.
Message	Processing downloaded data
Error	NSE Processor cannot open temporary bhavcopy file
Error	Could not find file 'H:\Bhavcopy\temp\NSEbhav.gbc'.
Message	Downloading NSE Futures Bhavcopy
Error	Error downloading NSE Futures Bhavcopy file
Error	The remote server returned an error: (503) Server

**Comment by arunbssr** [comment]
EOD downloading working now. Check now, friends.
