### ISSUE TITLE
Error downloading bhavcopy

### ISSUE THREAD

**Issue by mmphadke** [hemenkapadia/getbhavcopy#21]
Shows Error checking version support for Getbhavcopy using Github API..
Same even after taking latest version.

**Comment by hemenkapadia** [comment]
@mmphadke, I am working on the next version and hence caused this issue. I have reverted back the 2.1.10a value in the version check routine so 2.1.10a should start working now.

Next version 2.1.11a with the BSE fix should be out in a couple of days.

Closing the issue
