### ISSUE TITLE
error in downloading bhavcopy data since 29.3.2023

### ISSUE THREAD

**Issue by mehul-bosamia** [hemenkapadia/getbhavcopy#218]
while downloading nse equity bhav copy - 
it gives error message  - could not extract nse zip file & could not find central directory. 
please help.

**Comment by niteshmurti** [comment]
this probably has something to do with the old nse website being now permanently shutdown. I went to options in getbhavcopy and switched to the new website but it's still not working.

**Comment by madhanji** [comment]
**from 31.03.2023 Eod file not download, Nse maybe changed their url, i changed the url in getbhavcopy but not success**.
dear Heman..pls look in to it ji

**Comment by bijoy2526** [comment]
same problem again.not working.

**Comment by bijoy2526** [comment]
becoming tough when it does not wok to find alternate.

**Comment by bijoy2526** [comment]
can any one please provide datas for amibroker for last 2 trading session.I tried to down load from nse site,
[cm31MAR2023bhav.csv](https://github.com/hemenkapadia/getbhavcopy/files/11132656/cm31MAR2023bhav.csv)
but it has mixed up datas ,in addition to equity others are there,can one help ?Before Hemenji could find out a solution.so that we can manage.

**Comment by bijoy2526** [comment]
only equity can be filtered.little more help needed.

**Comment by shaikhmdimran** [comment]
Sharing 28th March to 31st March 2023 files, manual work is required to convert them in Txt to upload.
[2023-03-31-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134413/2023-03-31-NSE-EQ.txt)
[2023-03-28-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134414/2023-03-28-NSE-EQ.txt)
[2023-03-29-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134415/2023-03-29-NSE-EQ.txt)

**Comment by imcandlestick** [comment]
> Sharing 28th March to 31st March 2023 files, manual work is required to convert them in Txt to upload. [2023-03-31-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134413/2023-03-31-NSE-EQ.txt) [2023-03-28-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134414/2023-03-28-NSE-EQ.txt) [2023-03-29-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134415/2023-03-29-NSE-EQ.txt)

thank you.. how did you downloaded them?

**Comment by alferns15** [comment]
Thank you guys for providing NSE-EQ.txt files.
Could you also provide NSE-FO.txt files. Thanking you again.

**Comment by mehul-bosamia** [comment]
> Sharing 28th March to 31st March 2023 files, manual work is required to convert them in Txt to upload. [2023-03-31-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134413/2023-03-31-NSE-EQ.txt) [2023-03-28-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134414/2023-03-28-NSE-EQ.txt) [2023-03-29-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134415/2023-03-29-NSE-EQ.

**Comment by mehul-bosamia** [comment]
> Sharing 28th March to 31st March 2023 files, manual work is required to convert them in Txt to upload. [2023-03-31-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134413/2023-03-31-NSE-EQ.txt) [2023-03-28-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134414/2023-03-28-NSE-EQ.txt) [2023-03-29-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11134415/2023-03-29-NSE-EQ.txt)

Thank You. But it does not includes indices. how to insert indices data please explain.

**Comment by kbs7010** [comment]
> 

From where you download files?

**Comment by kbs7010** [comment]
Sharing 05-april-2023 file ,manual work is required to convert them in Txt to upload.
[2023-04-05-NSE-EQ.txt](https://github.com/hemenkapadia/getbhavcopy/files/11160864/2023-04-05-NSE-EQ.txt)

**Comment by DatapulseEOD** [comment]
If you are still getting the 'Could not extract NSE zip file' error or struggling with the new CM-UDIFF format parsing, there is a simpler way to get your data without constantly patching software. just grab the standard OHLC text layout files daily
https://tinyurl.com/4wm85vyb

Check this

[2026-03-17-NSE-EQ.txt](https://github.com/user-attachments/files/26178321/2026-03-17-NSE-EQ.txt)
[2026-03-18-NSE-EQ.txt](https://github.com/user-attachments/files/26178319/2026-03-18-NSE-EQ.txt)
[2026-03-19-NSE-EQ.txt](https://github.com/user-attachments/files/26178322/2026-03-19-NSE-EQ.txt)
[2026-03-20-NSE-EQ.txt](https://github.com/user-attachments/files/26178320/2026-03-20-NSE-EQ.txt)
