### ISSUE TITLE
Unable to download bhavcopy

### ISSUE THREAD

**Issue by hrishisukhada** [hemenkapadia/getbhavcopy#22]
Respected Sir,

I got a message to download latest version of getbhavcopy. I downloaded new version from your website however, I am still getting the same message and unable to download bhavcopy. I have attached the screenshot. Please help.
![getbhavcopy issue](https://user-images.githubusercontent.com/28752905/36638951-350d3d96-1a27-11e8-9459-8323fb63a4c6.jpg)

**Comment by hemenkapadia** [comment]
hi @hrishisukhada - this happened because i changed the version check string while working on the next version. I have reverted back the old version, so it should work now.

I will release the fixed next version 2.1.11a in next couple of days.
