### ISSUE TITLE
Download issue with getbhavcopy version 2.1.11a

### ISSUE THREAD

**Issue by crapkachra** [hemenkapadia/getbhavcopy#27]
Hi
While downloading, I get the following error messages
Message	Error checking version support for Getbhavcopy using Github API.
Message	Unable to connect to the remote server
Message	Checking with Raw Github content
Message	Error checking version support for Getbhavcopy using Raw Github content.
Message	Unable to connect to the remote serve

I am using Windows 7 Professional. Have not been able to download sicne March 2nd, 2018. Would you be able to help please. BTW - I have also contributed to appreciate your good work via paypal.
Thanks

**Comment by hemenkapadia** [comment]
Are you able to access www.getbhavcopy.com/release.txt from your browser
when you get this message ?

**Comment by crapkachra** [comment]
Hi Hemen,

 

Here is an extract from the release.txt

 

{

  "tag_name": "2.1.11a",

  "name": "Getbhavcopy version 2.1.11a"

}

 

 

Thanks

Hemant M

**Comment by raoge** [comment]
I am also receiving the same error message as below after starting the downlad.
Message	*********  Starting Getbhavcopy  *********
Message	Error checking version support for Getbhavcopy using Github API.
Message	The request was aborted: Could not create SSL/TLS secure channel.
Message	Checking with Raw Github content.

Message	Downloading BSE Equity Bhavcopy
Error	Error getting VIEWSTATE information for Index Data HTTP POST for SENSEX
Error	The remote server returned an error: (301) Moved Permanently Redirect.

**Comment by hemenkapadia** [comment]
@raoge , the BSE indices issue you report is tracked in issue #46 

The issue discussed above is something different. This issue is about sometime GBC cannot even perform version check with the static approach. Not sure what could cause this.

For now, tagged to backlog

**Comment by hemenkapadia** [comment]
Original issue reported is same as issue #29, where Getbhavcopy is unable to communicate with Github API endpoint over HTTPs due to lack of TLS 1.2 support in .NET 4.0. Will be fixed in 2.1.12a

**Comment by hemenkapadia** [comment]
Closing as fixed in code. Waiting for release.
