### ISSUE TITLE
BSE Downloading takes too long

### ISSUE THREAD

**Issue by ankush30** [hemenkapadia/getbhavcopy#30]
The data downloading from NSE for single day is just 2-3s but for BSE downloaing all indexes it takes sometime 2-3 min and I have optic fibre broadband network. 

- Is there any selection which can avoid downloading BSE indexes. some of indexes are always giving errOR so that time can be saved if we can select which index to download.

Just enclosing the logs for some error frequently encountered. 
--------------------------------------------------------------------------

Error	Error sending Index Data HTTP POST for AUTO
Error	The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
Message	Downloading index data for MIDCAP
Error	Error sending Index Data HTTP POST for MIDCAP
Error	The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.

**Comment by tjagad** [comment]
Even I've observed this lately. I'm not sure it's the issue with BSE server or getbhavcopy.

**Comment by el-otaku** [comment]
True that. 

BSE data is taking forever to download.

**Comment by ankush30** [comment]
Infact shorter solution would be to make the indexes optional. Most of time is being consumed in downloading indexes and some of them do given errors inherently.

**Comment by hemenkapadia** [comment]
Tagging to 2.1.12a. Should get fixed as BSE indices download needs to be rewritten.

**Comment by hemenkapadia** [comment]
Closing for now as BSE Indices data download login is re-written as per issue #46 . This should be closed IMHO. @ankush30 , reopen if needed
