### ISSUE TITLE
Error NSE server did not return data for index NSEMIDCAP Error NSE server did not return data for index NIFTYSMALL100

### ISSUE THREAD

**Issue by devismodi** [hemenkapadia/getbhavcopy#33]
Error NSE server did not return data for index NSEMIDCAP
Error NSE server did not return data for index NIFTYSMALL100

**Comment by devismodi** [comment]
Date 02/04/2018 to till date
Error NSE server did not return data for index NSEMIDCAP
Error NSE server did not return data for index NIFTYSMALL100

**Comment by amit2019** [comment]
hello sir 

same problem i m facing. how to resolve it.

Error Nse Server did not return data for index is showing at the time of downloading data

**Comment by hemenkapadia** [comment]
Tagging to 2.1.12a milestone. Investigate and fix

**Comment by hemenkapadia** [comment]
All NSE Indices revised to match with dropdown list https://www.nseindia.com/products/content/equities/indices/historical_index_data.htm

**Comment by ghost** [comment]
Hi,

Right now, I am getting the following errors

Error	NSE server did not return data for index NIFTYSMALLCAP250
Error	NSE server did not return data for index NIFTYSMALLCAP50
Error	NSE server did not return data for index NIFTYMIDSMALLCAP400
Error	NSE server did not return data for index NIFTYALPHALOWVOL30
Error	NSE server did not return data for index NIFTY200QUALITY30


Jignesh
