### ISSUE TITLE
Not downloading Delivery volume

### ISSUE THREAD

**Issue by coolkal** [hemenkapadia/getbhavcopy#37]
GBC not downloading delivery volume data since 18-07-2018 (500) Internal server error being shown

**Comment by tjagad** [comment]
Yes observing the same at my end as well.

**Comment by coolkal** [comment]
Now will take ages to resolve, if at all

**Comment by coolkal** [comment]
How long does it take to change a single link? If you provide the list of links in GBC we could do it ourselves

**Comment by MA5YK** [comment]
Any update on this issue?

**Comment by hemenkapadia** [comment]
Need to understand the issue for fix , should be targeted in 2.1.12a? What does delivery volume mean here? Is this for NSE or BSE or NSE Futures ? 

Any comments @coolkal @tjagad @MA5YK ; I am working on 2.1.12a to get Getbhavcopy working for BSE Indices and need to understand the exact issue here to be able to fix it.

**Comment by tjagad** [comment]
Hi Hemen,

The delivery volume in this context refers to the portion of the traded volume on NSE taken up for delivery as compared to intraday buying and selling. This csv files gives the information about deliveryable quantity https://www.nseindia.com/products/content/sec_bhavdata_full.csv

**Comment by MA5YK** [comment]
Delivery quantity for NSE stocks. 

Also found at https://www.nseindia.com/products/content/equities/equities/archieve_eq.htm by selecting "Security-wise Delivery Position" report. Note this report does not have "BE" security type. 

Thanks.

**Comment by hemenkapadia** [comment]
This has to do with Open Interest data download failing. Due to an error in the error message text, this was showing up as VIX data download failure, but it was Open Interest data download that was failing.

**Comment by hemenkapadia** [comment]
Fixed . Waiting for build and release of 2.1.12a.
