### ISSUE TITLE
Thank you for this wonderful tool

### ISSUE THREAD

**Issue by ajeet1984** [hemenkapadia/getbhavcopy#38]
First of thank you for this wonderful tool. Many people like me who are beginners much appreciate it. Just one question for  NIFTY 50 there are plenty of indices but can't find NSE NIFTY so how to download it. Please guide me. Thanks again

**Comment by hemenkapadia** [comment]
@ajeet1984 , Not sure what you do you mean. NSENIFTY is the first index downloaded for NSE. Can you explain the issue if it still exists? If no longer an issue, please suggest if the issue can be closed.

**Comment by hemenkapadia** [comment]
Closing as no response.
