### ISSUE TITLE
Future Near Month Data issue

### ISSUE THREAD

**Issue by sgupta110** [hemenkapadia/getbhavcopy#39]
Data Download has issue in all Near Month FO data.
Please help resolve.

Contract I is recorded under III as below:
APOLLOTYRE-III,20180814,263.5,268.7,262.95,268.05,3031,11355000
APOLLOTYRE-I,20180814,265.25,269.4,265.25,268.65,31,309000
APOLLOTYRE-II,20180814,0,0,0,262.65,0,6000

and some are also getting recorded under II
BRITANNIA-II,20180814,6482.1,6509.75,6455,6483.95,1438,1318800
BRITANNIA-III,20180814,6502.1,6538.75,6486.6,6523.15,17,17800
BRITANNIA-I,20180814,0,0,0,6500,0,1000

**Comment by hemenkapadia** [comment]
Closing as duplicate if issue #11
