### ISSUE TITLE
CANNOT CREATE LOG.TXT >> NOT ABLE TO DOWNLOAD DATA PL HELP 

### ISSUE THREAD

**Issue by RAHULCHAWDHARY** [hemenkapadia/getbhavcopy#40]
Dear Hemenji,
Cannot download. App not able to create log.txt on win 10. Please see the attached file. 
[ERROR.docx](https://github.com/hemenkapadia/getbhavcopy/files/2290664/ERROR.docx)

**Comment by vasudev49** [comment]
I had a similar issue. Then I realised that if you search for the executable and directly double click on it to start the program the issue didnt come. The issue comes when you try to access the executable through searching on windows Start.

**Comment by vasudev49** [comment]
ok I just saw your error. did you delete the 'logs' folder under BHAVCOPY? Try create the folder 'logs' inside the BHAVCOPY folder.

**Comment by hemenkapadia** [comment]
@RAHULCHAWDHARY , are you still facing the issue. Can you confirm the path mentioned in the log does exist and is accessible  to the user ? Can you try creating the logs folder there ?

**Comment by hemenkapadia** [comment]
Closing as no response. Not sure what the error is. Cannot reproduce and no widespread occurrences reported.
