### ISSUE TITLE
GBC stuck at ***Starting Getbhavcopy*** page

### ISSUE THREAD

**Issue by horizonviewer** [hemenkapadia/getbhavcopy#43]
Hi,
I was successfully using this too for the last 2 months, but when I tried to use it today, it did not go past the "Starting Getbhavcopy" screen. It is stuck there for close to an hour now. I tried restarting, resinstalling.. etc, but nothing helped.
The date selection pane is also greyed out, and the download button is disabled.
Please help on how to get this back working.
Many thanks is advance!!!
![gbc screenshot](https://user-images.githubusercontent.com/30177573/45775342-213e7a80-bc6d-11e8-93c6-ee28a92068cb.JPG)

**Comment by ke-senthilkumar** [comment]
Use the Options button to save the location, what to download, etc and then try the date button & download. I think it requires configuration.

**Comment by hemenkapadia** [comment]
Hi @horizonviewer , are you still facing the issue? did you try setting the options as suggested by @ke-senthilkumar ?

If it works please let us know/close the issue.

**Comment by hemenkapadia** [comment]
Closing as no response.
