### ISSUE TITLE
cylancePROTECT flags getbhavcopy as unsafe

### ISSUE THREAD

**Issue by tjagad** [hemenkapadia/getbhavcopy#44]
For some reason getbhavcopy executable is flagged as unsafe by cylancePROTECT antivirus. Kindly check.

**Comment by hemenkapadia** [comment]
The only place where Getbhavcopy should be downloaded from is https://github.com/hemenkapadia/getbhavcopy/releases.

If you have obtained Getbhavcopy from the release page then I can guarantee its safety as long as you also check the MD5 of the zip and exe and they match.

The virus total link for Getbhavcopy 2.1.11a is below
https://www.virustotal.com/#/file/4810c056018af83eb8a7005b558fd5ccbecb374ceb96ca0296035f5e09196e3e/detection

False positive is a common issue with antivirus. Read more about it https://www.pcworld.com/article/2883692/virustotal-tackles-false-positive-malware-detections-plaguing-antivirus-and-software-vendors.html

So as long as you obtain GBC from the official source, you should be ok.

Closing the issue.
