### ISSUE TITLE
Issue downloading data from  v.2.1.9a

### ISSUE THREAD

**Issue by lestat-rnt** [hemenkapadia/getbhavcopy#45]
Hi Mr. Kapadia et all, 

I was having trouble downloading the data using the Getbhavcopy app. I have checked my .Net version, ensuring it is the latest, checked and reviewed the protocol to create the various folders(NSE, BSE, Fut.), linking them on the app but am running into some trouble. 

Apologies if this issue has been previously addressed, however, I went through the previous posts but couldn't find a troubleshooting solution. I can confirm that I am able to pull up the .text on the web browser as suggested in a previous response by you.

Here are details from the log : 
11/24/2018 18:30:56	Message	*********  Starting Getbhavcopy  *********
11/24/2018 18:31:17	Message	Settings Saved
11/24/2018 18:31:46	Message	Settings Saved
11/24/2018 18:31:55	Message	Error checking version support for Getbhavcopy using Github API.
**11/24/2018 18:31:55	Message	The request was aborted: Could not create SSL/TLS secure channel.**
11/24/2018 18:31:55	Message	Checking with Raw Github content
11/24/2018 18:31:56	Message	*********  Downloading Data for 23-11-2018  *********
11/24/2018 18:31:56	Message	Downloading NSE Equity Bhavcopy
11/24/2018 18:31:56	Error	Error downloading NSE Equity Bhavcopy file
11/24/2018 18:31:56	Error	The remote server returned an error: (404) Not Found.

Any guidance is most appreciated. Have a great week ahead.

Regards

**Comment by ke-senthilkumar** [comment]
Pls try the latest version. 2.1.11a. I was able to download till 23-11-2018.

**Comment by lestat-rnt** [comment]
Thank you Mr. Kumar, 
I appreciate you taking the time to point out my error. Have a great week ahead.
Regards
