### ISSUE TITLE
Getbhavcopy version 2.1.12a - BSE Index download getting stuck at SENSEX

### ISSUE THREAD

**Issue by Krunal134** [hemenkapadia/getbhavcopy#53]
Not Able TO Download Data From BSE  ... Stuck AT " Message	Downloading index data for SENSEX "

Log :

Message	*********  Downloading Data for 21-01-2019  *********
Message	Downloading NSE Equity Bhavcopy
Message	Downloading index data for NSENIFTY
Message	Downloading index data for NIFTYJUNIOR
Message	Downloading index data for NIFTYMIDCAPLIQ15
Message	Downloading index data for NSE100
Message	Downloading index data for NIFTY200
Message	Downloading index data for NSE500
Message	Downloading index data for NSEMIDCAP150
Message	Downloading index data for MIDCAP50
Message	Downloading index data for NSEMIDCAP
Message	Downloading index data for NIFTYSMALLCAP250
Message	Downloading index data for NIFTYSMALLCAP50
Message	Downloading index data for NSESMLCAP100
Message	Downloading index data for NIFTYLARGEMIDCAP250
Message	Downloading index data for NIFTYMIDSMALLCAP400
Message	Downloading index data for NIFTYAUTO
Message	Downloading index data for BANKNIFTY
Message	Downloading index data for NIFTYFINSERVICE
Message	Downloading index data for NIFTYFMGC
Message	Downloading index data for NSEIT
Message	Downloading index data for NIFTYMEDIA
Message	Downloading index data for NIFTYMETAL
Message	Downloading index data for NIFTYPHARMA
Message	Downloading index data for NIFTYPVTBANK
Message	Downloading index data for NIFTYPSUBANK
Message	Downloading index data for NIFTYREALTY
Message	Downloading index data for NIFTYCOMMODITIES
Message	Downloading index data for NIFTYCONSUMPTION
Message	Downloading index data for NIFTYCPSE
Message	Downloading index data for NIFTYENERGY
Message	Downloading index data for NIFTY100ESG
Message	Downloading index data for NIFTY100ENHESG
Message	Downloading index data for NIFTYINFRA
Message	Downloading index data for NIFTYMNC
Message	Downloading index data for NIFTYPSE
Message	Downloading index data for NIFTYSMEEMERGE
Message	Downloading index data for NIFTYSERVSECTOR
Message	Downloading index data for NIFTYSHARIAH25
Message	Downloading index data for NIFTY50SHARIAH
Message	Downloading index data for NIFTY500SHARIAH
Message	Downloading index data for NIFTYABGROUP
Message	Downloading index data for NIFTYMAHINDRA
Message	Downloading index data for NIFTYTATA
Message	Downloading index data for NIFTYTATA25CAP
Message	Downloading index data for NIFTYABGROUP
Message	Downloading index data for NIFTYLIQ15
Message	Downloading index data for NIFTY500VALUE50
Message	Downloading index data for NIFTYALPHALOWVOL30
Message	Downloading index data for NIFTYQUALLOWVOL30
Message	Downloading index data for NIFTYALPHAQUALLOWVOL30
Message	Downloading index data for NIFTYALPHAQUALVALLOWVOL30
Message	Downloading index data for NIFTY50EQUALWEIGHT
Message	Downloading index data for NIFTY100EQUALWEIGHT
Message	Downloading index data for NIFTY100LOWVOL30
Message	Downloading index data for NSEDEFTY
Message	Downloading index data for NIFTY50DIVPOINT
Message	Downloading index data for NIFTYDIVOPPS50
Message	Downloading index data for NIFTYALPHA50
Message	Downloading index data for NIFTY50ARBITRAGE
Message	Downloading index data for NIFTY50FUTINDEX
Message	Downloading index data for NIFTY50FUTTRINDEX
Message	Downloading index data for NIFTYHIGHBETA50
Message	Downloading index data for NIFTYLOWVOL50
Message	Downloading index data for NIFTY200QUALITY30
Message	Downloading index data for NIFTY50VALUE20
Message	Downloading index data for NIFTYGROWSECT15
Message	Downloading index data for NIFTY50TR2XLEV
Message	Downloading index data for NIFTY50PR2XLEV
Message	Downloading index data for NIFTY50TR1XINV
Message	Downloading index data for NIFTY50PR1XINV
Message	Downloading index data for NIFTY-GS-COMPSITE
Message	Downloading index data for NIFTY-GS-4-8YR
Message	Downloading index data for NIFTY-GS-8-13YR
Message	Downloading index data for NIFTY-GS-10YR
Message	Downloading index data for NIFTY-GS-10YR-CLN
Message	Downloading index data for NIFTY-GS-11-15YR
Message	Downloading index data for NIFTY-GS-15YRPLUS
Message	Downloading index data for VIX
Message	Processing downloaded data
Message	*********  NSE Equity Bhavcopy file generated  *********
Message	Downloading BSE Equity Bhavcopy
Message	Downloading index data for SENSEX

**Comment by hemenkapadia** [comment]
Just tested on 2.1.12a. Seems working fine for me 
```
Message	*********  Starting Getbhavcopy  *********
Message	*********  Downloading Data for 21-01-2019  *********
Message	Downloading NSE Equity Bhavcopy
Message	Downloading index data for NSENIFTY
Message	Downloading index data for NIFTYJUNIOR
Message	Downloading index data for NIFTYMIDCAPLIQ15
Message	Downloading index data for NSE100
Message	Downloading index data for NIFTY200
Message	Downloading index data for NSE500
Message	Downloading index data for NSEMIDCAP150
Message	Downloading index data for MIDCAP50
Message	Downloading index data for NSEMIDCAP
Message	Downloading index data for NIFTYSMALLCAP250
Message	Downloading index data for NIFTYSMALLCAP50
Message	Downloading index data for NSESMLCAP100
Message	Downloading index data for NIFTYLARGEMIDCAP250
Message	Downloading index data for NIFTYMIDSMALLCAP400
Message	Downloading index data for NIFTYAUTO
Message	Downloading index data for BANKNIFTY
Message	Downloading index data for NIFTYFINSERVICE
Message	Downloading index data for NIFTYFMGC
Message	Downloading index data for NSEIT
Message	Downloading index data for NIFTYMEDIA
Message	Downloading index data for NIFTYMETAL
Message	Downloading index data for NIFTYPHARMA
Message	Downloading index data for NIFTYPVTBANK
Message	Downloading index data for NIFTYPSUBANK
Message	Downloading index data for NIFTYREALTY
Message	Downloading index data for NIFTYCOMMODITIES
Message	Downloading index data for NIFTYCONSUMPTION
Message	Downloading index data for NIFTYCPSE
Message	Downloading index data for NIFTYENERGY
Message	Downloading index data for NIFTY100ESG
Message	Downloading index data for NIFTY100ENHESG
Message	Downloading index data for NIFTYINFRA
Message	Downloading index data for NIFTYMNC
Message	Downloading index data for NIFTYPSE
Message	Downloading index data for NIFTYSMEEMERGE
Message	Downloading index data for NIFTYSERVSECTOR
Message	Downloading index data for NIFTYSHARIAH25
Message	Downloading index data for NIFTY50SHARIAH
Message	Downloading index data for NIFTY500SHARIAH
Message	Downloading index data for NIFTYABGROUP
Message	Downloading index data for NIFTYMAHINDRA
Message	Downloading index data for NIFTYTATA
Message	Downloading index data for NIFTYTATA25CAP
Message	Downloading index data for NIFTYABGROUP
Message	Downloading index data for NIFTYLIQ15
Message	Downloading index data for NIFTY500VALUE50
Message	Downloading index data for NIFTYALPHALOWVOL30
Message	Downloading index data for NIFTYQUALLOWVOL30
Message	Downloading index data for NIFTYALPHAQUALLOWVOL30
Message	Downloading index data for NIFTYALPHAQUALVALLOWVOL30
Message	Downloading index data for NIFTY50EQUALWEIGHT
Message	Downloading index data for NIFTY100EQUALWEIGHT
Message	Downloading index data for NIFTY100LOWVOL30
Message	Downloading index data for NSEDEFTY
Message	Downloading index data for NIFTY50DIVPOINT
Message	Downloading index data for NIFTYDIVOPPS50
Message	Downloading index data for NIFTYALPHA50
Message	Downloading index data for NIFTY50ARBITRAGE
Message	Downloading index data for NIFTY50FUTINDEX
Message	Downloading index data for NIFTY50FUTTRINDEX
Message	Downloading index data for NIFTYHIGHBETA50
Message	Downloading index data for NIFTYLOWVOL50
Message	Downloading index data for NIFTY200QUALITY30
Message	Downloading index data for NIFTY50VALUE20
Message	Downloading index data for NIFTYGROWSECT15
Message	Downloading index data for NIFTY50TR2XLEV
Message	Downloading index data for NIFTY50PR2XLEV
Message	Downloading index data for NIFTY50TR1XINV
Message	Downloading index data for NIFTY50PR1XINV
Message	Downloading index data for NIFTY-GS-COMPSITE
Message	Downloading index data for NIFTY-GS-4-8YR
Message	Downloading index data for NIFTY-GS-8-13YR
Message	Downloading index data for NIFTY-GS-10YR
Message	Downloading index data for NIFTY-GS-10YR-CLN
Message	Downloading index data for NIFTY-GS-11-15YR
Message	Downloading index data for NIFTY-GS-15YRPLUS
Message	Downloading index data for VIX
Message	Downloading Deliverable Quantity(Open Interest) data
Message	Processing downloaded data
Message	*********  NSE Equity Bhavcopy file generated  *********
Message	Downloading NSE Futures Bhavcopy
Message	Processing downloaded data
Message	*********  NSE Futures Bhavcopy file generated  *********
Message	Downloading BSE Equity Bhavcopy
Message	Downloading index data for SENSEX
Message	Downloading index data for BSE-100
Message	Downloading index data for BSE-200
Message	Downloading index data for BSE-500
Message	Downloading index data for ALLCAP
Message	Downloading index data for AUTO
Message	Downloading index data for BANKEX
Message	Downloading index data for BASICMAT
Message	Downloading index data for CAPGOODS
Message	Downloading index data for CONDDISC
Message	Downloading index data for CONSDURBL
Message	Downloading index data for CPSE
Message	Downloading index data for DOL-30
Message	Downloading index data for DOL-100
Message	Downloading index data for DOL-200
Message	Downloading index data for ENERGY
Message	Downloading index data for FMCG
Message	Downloading index data for FINANCE
Message	Downloading index data for HLTHCARE
Message	Downloading index data for INFRA
Message	Downloading index data for MANUFACTURING
Message	Downloading index data for INDUSTRIAL
Message	Downloading index data for IT
Message	Downloading index data for METAL
Message	Downloading index data for MIDCAP
Message	Downloading index data for SMLCAP
Message	Downloading index data for OILGAS
Message	Downloading index data for POWER
Message	Downloading index data for PSU
Message	Downloading index data for REALTY
Message	Downloading index data for TECK
Message	Downloading index data for TELECOM
Message	Downloading index data for UTILITIES
Message	Downloading index data for CARBONEX
Message	Downloading index data for GREENEX
Message	Processing downloaded data
Message	*********  BSE Equity Bhavcopy file generated  *********
Message	********* Data download complete *********
```
![image](https://user-images.githubusercontent.com/9943123/51558834-4b7b9100-1e35-11e9-90c6-7a13066f1065.png)

**Comment by subhroleo1** [comment]
Hi Sir,

For me, it is getting stuck here

![image](https://user-images.githubusercontent.com/46937804/51561628-bcf72600-1ead-11e9-8dac-0c35e5422547.png)

**Comment by Krunal134** [comment]
> Just tested on 2.1.12a. Seems working fine for me
> 
> ```
> Message	*********  Starting Getbhavcopy  *********
> Message	*********  Downloading Data for 21-01-2019  *********
> Message	Downloading NSE Equity Bhavcopy
> Message	Downloading index data for NSENIFTY
> Message	Downloading index data for NIFTYJUNIOR
> Message	Downloading index data for NIFTYMIDCAPLIQ15
> Message	Downloading index data for NSE100
> Message	Downloading index data for NIFTY200
> Message	Downloading index data for NSE500
> Message	Downloading index data for NSEMIDCAP150
> Message	Downloading index data for MIDCAP50
> Message	Downloading index data for NSEMIDCAP
> Message	Downloading index data for NIFTYSMALLCAP250
> Message	Downloading index data for NIFTYSMALLCAP50
> Message	Downloading index data for NSESMLCAP100
> Message	Downloading index data for NIFTYLARGEMIDCAP250
> Message	Downloading index data for NIFTYMIDSMALLCAP400
> Message	Downloading index data for NIFTYAUTO
> Message	Downloading index data for BANKNIFTY
> Message	Downloading index data for NIFTYFINSERVICE
> Message	Downloading index data for NIFTYFMGC
> Message	Downloading index data for NSEIT
> Message	Downloading index data for NIFTYMEDIA
> Message	Downloading index data for NIFTYMETAL
> Message	Downloading index data for NIFTYPHARMA
> Message	Downloading index data for NIFTYPVTBANK
> Message	Downloading index data for NIFTYPSUBANK
> Message	Downloading index data for NIFTYREALTY
> Message	Downloading index data for NIFTYCOMMODITIES
> Message	Downloading index data for NIFTYCONSUMPTION
> Message	Downloading index data for NIFTYCPSE
> Message	Downloading index data for NIFTYENERGY
> Message	Downloading index data for NIFTY100ESG
> Message	Downloading index data for NIFTY100ENHESG
> Message	Downloading index data for NIFTYINFRA
> Message	Downloading index data for NIFTYMNC
> Message	Downloading index data for NIFTYPSE
> Message	Downloading index data for NIFTYSMEEMERGE
> Message	Downloading index data for NIFTYSERVSECTOR
> Message	Downloading index data for NIFTYSHARIAH25
> Message	Downloading index data for NIFTY50SHARIAH
> Message	Downloading index data for NIFTY500SHARIAH
> Message	Downloading index data for NIFTYABGROUP
> Message	Downloading index data for NIFTYMAHINDRA
> Message	Downloading index data for NIFTYTATA
> Message	Downloading index data for NIFTYTATA25CAP
> Message	Downloading index data for NIFTYABGROUP
> Message	Downloading index data for NIFTYLIQ15
> Message	Downloading index data for NIFTY500VALUE50
> Message	Downloading index data for NIFTYALPHALOWVOL30
> Message	Downloading index data for NIFTYQUALLOWVOL30
> Message	Downloading index data for NIFTYALPHAQUALLOWVOL30
> Message	Downloading index data for NIFTYALPHAQUALVALLOWVOL30
> Message	Downloading index data for NIFTY50EQUALWEIGHT
> Message	Downloading index data for NIFTY100EQUALWEIGHT
> Message	Downloading index data for NIFTY100LOWVOL30
> Message	Downloading index data for NSEDEFTY
> Message	Downloading index data for NIFTY50DIVPOINT
> Message	Downloading index data for NIFTYDIVOPPS50
> Message	Downloading index data for NIFTYALPHA50
> Message	Downloading index data for NIFTY50ARBITRAGE
> Message	Downloading index data for NIFTY50FUTINDEX
> Message	Downloading index data for NIFTY50FUTTRINDEX
> Message	Downloading index data for NIFTYHIGHBETA50
> Message	Downloading index data for NIFTYLOWVOL50
> Message	Downloading index data for NIFTY200QUALITY30
> Message	Downloading index data for NIFTY50VALUE20
> Message	Downloading index data for NIFTYGROWSECT15
> Message	Downloading index data for NIFTY50TR2XLEV
> Message	Downloading index data for NIFTY50PR2XLEV
> Message	Downloading index data for NIFTY50TR1XINV
> Message	Downloading index data for NIFTY50PR1XINV
> Message	Downloading index data for NIFTY-GS-COMPSITE
> Message	Downloading index data for NIFTY-GS-4-8YR
> Message	Downloading index data for NIFTY-GS-8-13YR
> Message	Downloading index data for NIFTY-GS-10YR
> Message	Downloading index data for NIFTY-GS-10YR-CLN
> Message	Downloading index data for NIFTY-GS-11-15YR
> Message	Downloading index data for NIFTY-GS-15YRPLUS
> Message	Downloading index data for VIX
> Message	Downloading Deliverable Quantity(Open Interest) data
> Message	Processing downloaded data
> Message	*********  NSE Equity Bhavcopy file generated  *********
> Message	Downloading NSE Futures Bhavcopy
> Message	Processing downloaded data
> Message	*********  NSE Futures Bhavcopy file generated  *********
> Message	Downloading BSE Equity Bhavcopy
> Message	Downloading index data for SENSEX
> Message	Downloading index data for BSE-100
> Message	Downloading index data for BSE-200
> Message	Downloading index data for BSE-500
> Message	Downloading index data for ALLCAP
> Message	Downloading index data for AUTO
> Message	Downloading index data for BANKEX
> Message	Downloading index data for BASICMAT
> Message	Downloading index data for CAPGOODS
> Message	Downloading index data for CONDDISC
> Message	Downloading index data for CONSDURBL
> Message	Downloading index data for CPSE
> Message	Downloading index data for DOL-30
> Message	Downloading index data for DOL-100
> Message	Downloading index data for DOL-200
> Message	Downloading index data for ENERGY
> Message	Downloading index data for FMCG
> Message	Downloading index data for FINANCE
> Message	Downloading index data for HLTHCARE
> Message	Downloading index data for INFRA
> Message	Downloading index data for MANUFACTURING
> Message	Downloading index data for INDUSTRIAL
> Message	Downloading index data for IT
> Message	Downloading index data for METAL
> Message	Downloading index data for MIDCAP
> Message	Downloading index data for SMLCAP
> Message	Downloading index data for OILGAS
> Message	Downloading index data for POWER
> Message	Downloading index data for PSU
> Message	Downloading index data for REALTY
> Message	Downloading index data for TECK
> Message	Downloading index data for TELECOM
> Message	Downloading index data for UTILITIES
> Message	Downloading index data for CARBONEX
> Message	Downloading index data for GREENEX
> Message	Processing downloaded data
> Message	*********  BSE Equity Bhavcopy file generated  *********
> Message	********* Data download complete *********
> ```
> ![image](https://user-images.githubusercontent.com/9943123/51558834-4b7b9100-1e35-11e9-90c6-7a13066f1065.png)

NO SIR !! Not Downloading ...

**Comment by hemenkapadia** [comment]
What do you mean ? Logs screenshots do help me understand your problem

**Comment by Krunal134** [comment]
![untitled](https://user-images.githubusercontent.com/37530696/51594207-e9488c00-1f19-11e9-83ca-32c28216ed5d.jpg)

It Get Stuck @ " Message	Downloading index data for SENSEX"

**Comment by hemenkapadia** [comment]
While I understand you are facing the issue, I am not able to reproduce it. Everything works just fine for me.  I even tried connecting to India based VPN to see if India based IP are facing the issue, but everything works for me even in that case.

So the problem is if I cannot reproduce the problem, how do I analyze or fix it and then eventually test it before a release.

![image](https://user-images.githubusercontent.com/9943123/51660215-e40f2f80-1f61-11e9-90fc-585029a62d0a.png)

**Comment by hemenkapadia** [comment]
Possibly the TLS 1.2 hack is not properly supported on BSE server like it is supported on GitHub.

**Comment by Dakshesh01** [comment]
i am having same problem it was downloading in2.1.11 but not dowling in2.1.12

**Comment by madhanji** [comment]
what is the major changes in 2.1.12a ?
even u r count how many downloads using google analytics via?
so pls grant to use old version also..

**Comment by hemenkapadia** [comment]
closed
