### ISSUE TITLE
Not able to install ver 2.1.12a

### ISSUE THREAD

**Issue by mandarjoshi100** [hemenkapadia/getbhavcopy#54]
I downloaded the latest version zip file from github. but it does not contain getbhavcopy.exe, unlike in the past. not sure how to install the software. can you please provide installation instructions.

**Comment by hemenkapadia** [comment]
You need to download the following zip file from the Release section

![image](https://user-images.githubusercontent.com/9943123/51558623-c5f7e100-1e34-11e9-9e6c-6bd0c13da050.png)

**Comment by mandarjoshi100** [comment]
thanks for help. that worked.
