### ISSUE TITLE
GB V2.1.12A ERROR

### ISSUE THREAD

**Issue by madhanji** [hemenkapadia/getbhavcopy#55]
Dear hemang..
latestv2.1.12a have error on google analytics connection and some NSE indces not downloading like previous version..

A humble request most of them wanted and requested earlier about MCX& CURRENCY EOD data ,so this time pls make it with new version release..

Thanks

**Comment by Binay22Singh** [comment]
Sir download the file but its not working its says Getbhavcopy has stop working pl;z help

**Comment by hemenkapadia** [comment]
Same as #59  error connecting to Google Analytics. Closing as duplicate.
