### ISSUE TITLE
GB 2.1.12 a not working

### ISSUE THREAD

**Issue by SunilGoyal4** [hemenkapadia/getbhavcopy#58]
Dear Sir,

When starting GB it gives message as "Getbhavcopy has stopped working"

In View problem details are as follow:
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	getbhavcopy.exe
  Problem Signature 02:	2.1.12.39573
  Problem Signature 03:	5c46b130
  Problem Signature 04:	System
  Problem Signature 05:	4.0.0.0
  Problem Signature 06:	53b51323
  Problem Signature 07:	23b3
  Problem Signature 08:	1b
  Problem Signature 09:	System.NotSupportedException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	16393
  Additional Information 1:	abec
  Additional Information 2:	abecbc5f63be1ef86b00eed0c5362fc8
  Additional Information 3:	22ed
  Additional Information 4:	22ed9a265c4933842e8848a02a48563f

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Please rectify the problem.

Again thanking you for giving your valuable time.

Sunil Goyal

**Comment by hemenkapadia** [comment]
Please try installing dotNet Framework 4.0

https://www.microsoft.com/en-us/download/details.aspx?id=17718

**Comment by SunilGoyal4** [comment]
Dear Sir,

.net framework 4.0 alrready installed, old version was working fine.

Sunil Goyal

**Comment by toddkarrushi** [comment]
Same problem sir,
Getbhavcopy stopped working

Problem detail 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	getbhavcopy.exe
  Problem Signature 02:	2.1.12.39573
  Problem Signature 03:	5c46b130
  Problem Signature 04:	System
  Problem Signature 05:	4.0.0.0
  Problem Signature 06:	4ba1dff4
  Problem Signature 07:	1d21
  Problem Signature 08:	18
  Problem Signature 09:	System.NotSupportedException
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by hemenkapadia** [comment]
Could be due to the Microsoft.VisualBasic.dll included in this release. I was expecting that this will be provided by dotNet CLR. Not sure if merging this with the exe will help or not. Trying....

**Comment by SunilGoyal4** [comment]
okay sir, thanks for giving your valuable time.

**Comment by iiflvalsad** [comment]
Uninstall .net framework 4.0
Install .net framework 4.5

Issue will be solve

**Comment by SunilGoyal4** [comment]
Dear Sir,

Thanks, for NSE issue has been resolved but for BSE it stuck when
downloading Sensex:
Message *********  Downloading Data for 21-01-2019  *********
Message Downloading BSE Equity Bhavcopy
Message Downloading index data for SENSEX
already issue was raised by someone.

Thanks again as NSE data is mainly important.

Sunil Goyal

**Comment by hemenkapadia** [comment]
closed
