### ISSUE TITLE
Not working Getbhavcopy version 2.1.12a - Error connecting to Google Analytics

### ISSUE THREAD

**Issue by lksh3178** [hemenkapadia/getbhavcopy#59]
![getbhav](https://user-images.githubusercontent.com/46961901/51605305-b19b0d80-1f34-11e9-8626-95373fcdc180.png)

**Comment by hemenkapadia** [comment]
Are you guys behind a proxy ?

**Comment by madhanji** [comment]
HI hemankJi..
i am using on desktop, no proxy..but first day it was downloaded successfully,2nd day above lksh3178 screenshot error came..i redownloades and unzipped same folder with delete old..but no success..
internet is dls cable method.. no issues on inet..

**Comment by hemenkapadia** [comment]
Then I am out of wits. Software does not change like that. It is not able to communicate with the required servers.

**Comment by hemenkapadia** [comment]
Note to self - check if GA code used proxy as other parts of the code.

**Comment by iiflvalsad** [comment]
![screenshot_4](https://user-images.githubusercontent.com/47002657/51690146-2007ca80-201e-11e9-99ff-9de5e79ef2f1.jpg)
Not able to solve this error , please suggest what to do?

**Comment by hemenkapadia** [comment]
closed

**Comment by iiflvalsad** [comment]
let me check with new virsion of GBC

**Comment by iiflvalsad** [comment]
same problem with new virsion also .
Please help how to fix it.
![screenshot_5](https://user-images.githubusercontent.com/47002657/51924418-034f0680-2413-11e9-8cf2-d86bb163f855.jpg)

**Comment by hemenkapadia** [comment]
What is your windows version and .net framework version?

**Comment by hemenkapadia** [comment]
Is any data from nse and bse getting downloaded?

**Comment by iiflvalsad** [comment]
> Is any data from nse and bse getting downloaded?

 No , no download.
while launch getbhavcopy , it starts with error -Error Communication with google server, then it stopped by windows programme error.
