### ISSUE TITLE
Get Bhavcopy Downloader V.2.1.12a is not opening.

### ISSUE THREAD

**Issue by vivekmba05** [hemenkapadia/getbhavcopy#60]
Sir,

 New Version is not opening. It is asking for do you want to run this software. After Clicking Run, nothing is  opening.

![gbc](https://user-images.githubusercontent.com/46931266/51611646-bd430000-1f45-11e9-8a80-e2017e0dd0db.jpg)

**Comment by hemenkapadia** [comment]
Please extract the zip file and try executing the EXE. Also select Run, it is asking you for permissions if the file should be allowed to run or not.

**Comment by hemenkapadia** [comment]
Closing as no response + User should extract the zip file and select Run.
