### ISSUE TITLE
Getbhavcopy Data

### ISSUE THREAD

**Issue by Chirag9725** [hemenkapadia/getbhavcopy#61]
Dear Hemant Sir,

After downloading the latest version of Getbhavcopy 2.1.12a in that my data is showing from 21st Jan 2019 till 23rd Jan 2019.
Do help me in solve my query.

**Comment by hemenkapadia** [comment]
I don't understand your question/problem. Can you be more specific? Share the log or screenshot from Getbhavcopy.

**Comment by hemenkapadia** [comment]
Closing as no response.
