### ISSUE TITLE
Trouble with opening exe .message as 'getbhavcopy has encountered a problem and needs to close" 

### ISSUE THREAD

**Issue by karan1961** [hemenkapadia/getbhavcopy#62]
sir,
new version gives error as said.so far old version was working fine.Please help.

**Comment by hemenkapadia** [comment]
screenshot please. what is your os version?

**Comment by karan1961** [comment]
sir ,It is  XP in desktop. i know XP is out dated but i have few of my programs and software which works only on  XP .so utterly helpless as of now to change OS in desktop.Kindly help me out with this issue.Old version of Getbhavcopy " was working fine with XP.I would be highly obliged if this is resolved.If something can be done from your end as such that i can continue with old version..I would be grateful.I think there might be few people like me might be having such issue.Many thanks in advance ,sirRegardsKirti Patel 
 

    On Thursday, January 24, 2019 10:14 AM, Hemen Kapadia <notifications@github.com> wrote:
 

 screenshot please. what is your os version?—

**Comment by kvishal2001** [comment]
Hello,
I am facing same issue on my Windows xp. 
Regards.

**Comment by iiflvalsad** [comment]
.net framework 4.5 Required

Try it

**Comment by karan1961** [comment]
Let HK sir comment..however i appreciates your concern.too.Thanks! 

    On Thursday, January 24, 2019 9:27 PM, iiflvalsad <notifications@github.com> wrote:
 

 .net framework 4.5 RequiredTry it—

**Comment by karan1961** [comment]
however i tried to attach screenshot but somehow it does not work.still trying again.

**Comment by hemenkapadia** [comment]
Getbhavcopy so far and even the next version is built on .NET 4.0 which the highest version supported on XP. This was specifically done to support users who are still on XP.

Note that XP is no longer supported by Microsoft and it does not support TLS1.2 that is the basis of connecting to https websites and downloading data.

Keeping GBC on .net 4.0 is also causing development challenges, hence I have made a decision to move next builds of GBC to dotNet 4.6 and no longer support XP.

Version 2.1.13a should be considered the last version that should be assumed to base on dotNet 4.0.

See issue #67 and #24 for more information on how and why this decision is made.

I cannot guarantee 2.1.13a will work on XP, but I would be similar to 2.1.11a in terms of external dependencies, so i think it may work, but cannot be 100% sure.

**Comment by hemenkapadia** [comment]
closed

**Comment by karan1961** [comment]
Sir,Many thanks for taking pains irrespective of it works or not.But well the time and efforts  you took for this to resolve is worth appreciating.Regards
 

    On Sunday, January 27, 2019 7:07 AM, Hemen Kapadia <notifications@github.com> wrote:
 

 Getbhavcopy so far and even the next version is built on .NET 4.0 which the highest version supported on XP. This was specifically done to support users who are still on XP.Note that XP is no longer supported by Microsoft and it does not support TLS1.2 that is the basis of connecting to https websites and downloading data.Keeping GBC on .net 4.0 is also causing development challenges, hence I have made a decision to move next builds of GBC to dotNet 4.6 and no longer support XP.Version 2.1.13a should be considered the last version that should be assumed to base on dotNet 4.0.See issue #67 and #24 for more information on how and why this decision is made.I cannot guarantee 2.1.13a will work on XP, but I would be similar to 2.1.11a in terms of external dependencies, so i think it may work, but cannot be 100% sure.—
