### ISSUE TITLE
BSE Index data not being downloaded

### ISSUE THREAD

**Issue by brijwanth** [hemenkapadia/getbhavcopy#63]
BSE Index data is not at all being downloaded and getbhavcopy is getting stuck just there. I tried keeping it like that for around 2 hours but still it doesn't download single index. I have uploaded a screenshot for ready reference.
![stuck gb](https://user-images.githubusercontent.com/46984747/51653013-9f15e800-1fb7-11e9-96bc-2f314789587d.png)

**Comment by hemenkapadia** [comment]
Closed as duplicate of #53
