### ISSUE TITLE
Getbhavcopy_2.1.12a - Not working for Windows XP

### ISSUE THREAD

**Issue by kvishal2001** [hemenkapadia/getbhavcopy#65]
Hello, 
New version of Getbhavcopy_2.1.12a is not working. When I try to launch the exe file on my Windows XP it gives error message..."Getbhavecopy has encountered a problem it needs to close". 

The earlier version was working fine: Getbhavcopy_2.1.11a

Attached is the screenshot.

Kind Regards,
Kumar Vishal
M# 9931365872.

<img width="1440" alt="getbhavcopy" src="https://user-images.githubusercontent.com/46998665/51680233-3ce4d380-2007-11e9-9d1b-6fb81c73276d.png">

**Comment by hemenkapadia** [comment]
I am working for some of the fixes, but I will not be supporting Windows XP going ahead.

**Comment by hemenkapadia** [comment]
Closing as duplicate of #62 

Please see decision made for Windows XP.
