### ISSUE TITLE
Getbhavcopy_2.1.13a is not working in windows XP service pack 3

### ISSUE THREAD

**Issue by vlsijp** [hemenkapadia/getbhavcopy#71]
unable to open the Getbhavcopy_2.1.13a.exe file, it closes if try to open it. Getbhavcopy_2.1.11a was working well in XP
pls look into this issue and provide solution

**Comment by hemenkapadia** [comment]
Working on 2.14a

**Comment by hemenkapadia** [comment]
One possible reason could be the hack I introduced to somehow make TLS 1.2 working on Windows XP as recommended in 

https://stackoverflow.com/questions/33761919/tls-1-2-in-net-framework-4-0

Two things may have caused the failure. 
- Selecting only TLS1.2 as the code 3072 for SecurityProtol.
- And lack of support for TLS1.2 on Windows XP and dotNet 4.0 which is the last framework supported.

Could have implemented it as 
https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5

BSE and NSE support TLS1.0 to TLS 1.2, Github only supports TLS1.2. 
https://ssltools.digicert.com/checker/views/landing.jsp

So removed that code and went back to default. Everyone will have Github HTTPs error by the static version check (moved back to HTTP) should act as a fallback mechanism.

This should allow BSE and NSE to work and hopefully, GBC should be back to 2.1.11a on Windows XP but working for BSE indices.

**Comment by hemenkapadia** [comment]
Closed released 2.1.14a
