### ISSUE TITLE
Error in data import

### ISSUE THREAD

**Issue by Tj112** [hemenkapadia/getbhavcopy#79]
Hi Hemen

Thanks for all the good work being done by you.

On version 3.0.0a, 
i recently downloaded data for the last 1 month. When i am importing the same to Ami, it is giving an error - "invalid date format/value".

I have windows 10, amibroker 6.20.1

Do help 

Thanks in advance.

Regards

**Comment by Tj112** [comment]
![image](https://user-images.githubusercontent.com/47914458/53284316-af68e080-3778-11e9-90c1-17934dfcd7d2.png)

**Comment by hemenkapadia** [comment]
Hi @Tj112, can you try following these steps?

https://getbhavcopy.webs.com/importingtoamibroker.htm

**Comment by hemenkapadia** [comment]
Closing as no response
