### ISSUE TITLE
Issue in downloading data from BSE

### ISSUE THREAD

**Issue by dg2306** [hemenkapadia/getbhavcopy#8]
Message	Downloading BSE Equity Bhavcopy
Error	Error downloading BSE Equity Bhavcopy file
Error	The remote server returned an error: (400) Bad Request.
Message	Downloading index data for SENSEX
Error	Error sending Index Data HTTP POST for SENSEX
Error	The remote server returned an error: (400) Bad Request.
Message	Downloading index data for BSE-100
Error	Error sending Index Data HTTP POST for BSE-100
Error	The remote server returned an error: (400) Bad Request.
Message	Downloading index data for BSE-200

**Comment by dg2306** [comment]
Possibly issue with BSE website.

**Comment by tjagad** [comment]
I've raised an issue by which one can opt to retry downloading data. Lets hope that this request gets through. Link to the issue is https://github.com/hemenkapadia/getbhavcopy/issues/10

**Comment by hemenkapadia** [comment]
Possible duplicate of #10 

CC: @dg2306 , @tjagad

**Comment by hemenkapadia** [comment]
Closing issue as duplicate
