### ISSUE TITLE
Not able to import NSE-EOD in Amibroker

### ISSUE THREAD

**Issue by Dinprit** [hemenkapadia/getbhavcopy#83]
Hello Mr Hemen

**Not able to import NSE-EOD in Amibroker**
getting the following  error

Logging started for 'C:\Getbhavcopy\data\NSE-EOD\2019-03-13-NSE-EQ.txt' file, using format definition file 'Formats\GetBhavCopy.format'
Error in line <ticker>,<date>,<open>,<high>,<low>,<close>,<volume>,<o/i>
Invalid (close) price. Prices must be positive. If you want to import no quotation data please specify $NOQUOTES 1 ('no quotation data' box in Wizard)
Invalid date format/value

**Comment by hemenkapadia** [comment]
Take a look at the old documentation - that may help
https://getbhavcopy.webs.com/importingtoamibroker.htm
