### ISSUE TITLE
my antivirus removing the Getbhavcopy.exe file

### ISSUE THREAD

**Issue by patelashvin78** [hemenkapadia/getbhavcopy#84]
Please help my antivirus symantec endpoint protection removing Getbhavcopy.exe file.

**Comment by harjos** [comment]
I am also facing same issue. 
Please help

**Comment by hemenkapadia** [comment]
@patelashvin78  and @harjos - did you download Getbhavcopy from the release https://github.com/hemenkapadia/getbhavcopy/releases page? If yes then that is ok and nothing to worry as it is being detected as flase positive. You can mark the file as false positive and read the below documentation for the next steps.

- https://support.symantec.com/en_US/article.TECH98360.html
- https://support.symantec.com/en_US/article.TECH150607.html

NOTE - do this only if you have downloaded Getbhavcopy from the release section. If you downloaded it from some other website then that is not something released by me and can potentially be infected.

**Comment by patelashvin78** [comment]
Thanks for support but problem is my laptop is company provided and I don't
have admin rights for symantec.

Let me search for any alternative to bypass symantec.

Ashvin Patel

**Comment by hemenkapadia** [comment]
Sorry, cannot help here. Would advise using a personal machine if possible. Closing the issue.
