### ISSUE TITLE
Failed to download BSE Index Data

### ISSUE THREAD

**Issue by grumpy-goblin** [hemenkapadia/getbhavcopy#85]
![image](https://user-images.githubusercontent.com/45961709/55818428-38af5900-5b14-11e9-828a-f4fe1ed18acb.png)
BSE server not returning indices data, also there is no OI option [total delivery quantity] in BSE bhavcopy.

**Comment by hemenkapadia** [comment]
Closing. Looks like a server or connection error returned from the server (504). Not an issue with Getbhavcopy.
