### ISSUE TITLE
Error NSE server while downloading bhavcopy. Its taking lot of time

### ISSUE THREAD

**Issue by abhinkoi** [hemenkapadia/getbhavcopy#87]
Hi Hemen, 

First of all thank for you creating this wonderful tool to download bhavopy. I am using it for quite sometime & its really useful and easy. 
Offlate I started facing some issues during the download. It shows some error & due to this each day bhavcopy is taking lot of time to download (almost 1 minute per day whereas it should take few seconds). I want to download the data since the inception of our NSE Index so please guide.
Thanks in advance.
![image](https://user-images.githubusercontent.com/50546573/57582112-63f3e200-74de-11e9-95cd-6dea4e0d6705.png)

![image](https://user-images.githubusercontent.com/50546573/57582087-28f1ae80-74de-11e9-9c8d-dda282ce7a28.png)

**Comment by abhinkoi** [comment]
Hello Hemen,

Your quick response on this would be highly appreciated. Thanks in advance!

**Comment by abhinkoi** [comment]
Looks like nobody is here to look at the challenges posted & help resolve. Disappointing!

**Comment by hemenkapadia** [comment]
@abhinkoi,  there are various factors that could be at play here. How powerful machine you have, your internet speed, the time you are using Getbhavcopy to download the data, if there is an issue or overload on the NSE server at that time, etc. all can make a difference.

While there are other things I cannot control I recommend that you should use Getbhavcopy after 6 PM India time. Do not use it during exchange trading hours. 1 minute to download the full stock data and indices per day seems reasonable.

**Comment by hemenkapadia** [comment]
Let me know if you need any more help, if not I will close this issue.

**Comment by hemenkapadia** [comment]
Closing as no response.
