### ISSUE TITLE
nsenifty volume

### ISSUE THREAD

**Issue by ramkdlr** [hemenkapadia/getbhavcopy#9]
not fetching nsenifty volume data pls look into it from 9/11/2017.

**Comment by hemenkapadia** [comment]
While working on 2.1.11a, noticed that volume data is being downloaded for individual stocks as well as indices, including NSENIFTY.
```
ZYDUSWELL,20180220,1188,1299,1180,1259.65,131571,45126
ZYLOG,20180220,3.55,3.65,3.5,3.55,115715,67631
NSENIFTY,20180220,10391.00,10429.35,10347.65,10360.40,193464871,0
NIFTYJUNIOR,20180220,29211.90,29437.10,29081.10,29315.70,266466414,0
NIFTYLIQ15,20180220,4325.75,4355.80,4293.50,4311.35,115738688,0
```
The downloaded data matches with what is available on NSE website

![image](https://user-images.githubusercontent.com/9943123/36636550-d3f8830c-197d-11e8-9d0b-59b2b3b67a46.png)

Closing this issue, invalid bug filed.
