### ISSUE TITLE
Get Bhav Copy Not Opening after New .Net update 

### ISSUE THREAD

**Issue by BoyMumbai** [hemenkapadia/getbhavcopy#90]
Get Bhav Copy Not Opening after installing New .Net update received from Microsoft

**Comment by hemenkapadia** [comment]
Can you share more details? I checked on my machine Windows 10, with all latest updates turned on and it seems to work just fine.

**Comment by hemenkapadia** [comment]
Possible duplicate of #95. Closing as duplicate. @BoyMumbai, if you are still having issues please share the details on #95.
