### ISSUE TITLE
Even after donating the amount, bhavcopy software is not working..any clue?

### ISSUE THREAD

**Issue by satyamgargg** [hemenkapadia/getbhavcopy#91]

**Comment by hemenkapadia** [comment]
This has nothing to do with Donations. I never disable any functionality in Getbhavcopy with the intent of collecting money. The donation link is purely provided for those who want to contribute voluntarily.

**Comment by hemenkapadia** [comment]
possible duplicate of #95.

@satyamgargg, are you still having issues? Marking this as closed duplicate. We will discuss more about this in issue #95.
