### ISSUE TITLE
Not downloading NSE Indices

### ISSUE THREAD

**Issue by Rvgandhi** [hemenkapadia/getbhavcopy#92]
July 31 2019 ; GetBhavCopy is not downloading NSE Indices . Data for scrips is downloading fine
![image](https://user-images.githubusercontent.com/19625703/62263189-e71b3900-b438-11e9-9ede-e3bdd2ac3e37.png)

**Comment by el-otaku** [comment]
Ditto.

Working for past dates though.

**Comment by Rvgandhi** [comment]
Looks like NSEIndia may have had some issues with the files. Working ok today.. thanks
