### ISSUE TITLE
Download Button is disabled after donation

### ISSUE THREAD

**Issue by dbanerjee1410** [hemenkapadia/getbhavcopy#94]
Hi , 

Please note I have donated 10USD and still download button is disabled. Please Help.

**Comment by hemenkapadia** [comment]
This has nothing to do with Donations. I never disable any functionality in Getbhavcopy with the intent of collecting money. The donation link is purely provided for those who want to contribute voluntarily.

**Comment by hawaisanjay** [comment]
getbhavcopy not opening from 2 days, please help

**Comment by hemenkapadia** [comment]
@dbanerjee1410 - Are you still having issues? This has nothing to do with the donation. There many users of Getbhavcopy who continue to use it without any donation. I never disable any feature with the intent to collect the donation, else I would not have been giving it for free in the first place.

**Comment by hemenkapadia** [comment]
Will be closed soon if no response.

**Comment by hemenkapadia** [comment]
Closed as no response.
