### ISSUE TITLE
getbhavcopy not opening

### ISSUE THREAD

**Issue by hawaisanjay** [hemenkapadia/getbhavcopy#95]
Mine is windows 10. since two days getbhavcopy is not opening at all. Tried uninstalling and reinstalling. Please help

**Comment by hawaisanjay** [comment]
> will take a look this weekend.

thank you

**Comment by hemenkapadia** [comment]
I checked Getbhavcopy 3.0.0.26182 is working fine on Windows 10 version 1903. Are you still having issues? What is the problem? Can you share the screenshot or log?

**Comment by hawaisanjay** [comment]
sorry for late update. It was problem of antivirus. I was communicating with them. And they have updated antivirus. Now get bhavcopy is working fine.
Thanks

**Comment by hemenkapadia** [comment]
Great, closing the issue then.
