### ISSUE TITLE
new error while downloading 2019-10-30  

### ISSUE THREAD

**Issue by b4bhavinshah** [hemenkapadia/getbhavcopy#96]
![gbc](https://user-images.githubusercontent.com/57207877/67921492-ee83e700-fbcd-11e9-9162-54cff9158a2e.jpg)

**Comment by b4bhavinshah** [comment]
this was working fine till yesterday. thanks in advance

**Comment by hemenkapadia** [comment]
@b4bhavinshah, are you still getting the issue? I did a quick check and can download NSE and BSE data without any issue.

Here is the screenshot from me downloading the data for 8 Nov 2019.

![image](https://user-images.githubusercontent.com/9943123/68549401-4da2e200-03ac-11ea-8f4e-062d9ff99881.png)
