### ISSUE TITLE
data downloading error

### ISSUE THREAD

**Issue by dhawan09** [hemenkapadia/getbhavcopy#98]
hello
I am using widnows 7 32 bit and it does not support .net 4.6 version so I am no able to use latest Getbhavcopy_3.0.0a

I was using Getbhavcopy_2.1.15a but even this version is not able to download any data.

kindly help me with a solution

**Comment by hemenkapadia** [comment]
@dhawan09, I do not plan to back support Getbhavcopy versions.

.Net 4.6 is available on Windows 7 SP1. Not sure about the 32 bit part though (https://www.microsoft.com/en-us/download/details.aspx?id=53344). Are you sure that .net 4.6 or higher based applications do not work on your machine?

**Comment by dhawan09** [comment]
yes I'm sure... Have tried multiple times since you have launched the latest version but my system does not support .net 4.6 version.

Just a request if you could please solve the issue in version 2.1.15a.
I'll post the screenshot of error and even before it stopped working for nse and f&, bse data were not being downloaded since past few months. do check if possible

**Comment by dhawan09** [comment]
![gbc](https://user-images.githubusercontent.com/57316082/68689736-dc735280-0596-11ea-869b-0aa8856640f9.jpg)

**Comment by dhawan09** [comment]
kindly check the screenshot shared above

**Comment by dhawan09** [comment]
hello hemen
The issue is still on in latest version too... GBC stucks on downloading BSE SENXSEX data
I have upgraded to windows 7 sp 1 as of today
Microsoft .net 4.8 version in installed which is higher than the require 4.6 version

NSE AND F&O works as of now

**Comment by hemenkapadia** [comment]
Use version 3.0.1a. This should be fixed now.

**Comment by dhawan09** [comment]
using new version now on windows 10... bse data not downloading... stuck on downloading index data for sensex
